
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xfir.h"

/*
* The configuration table for devices
*/

XFir_Config XFir_ConfigTable[XPAR_XFIR_NUM_INSTANCES] =
{
	{
		XPAR_FIR_0_DEVICE_ID,
		XPAR_FIR_0_S_AXI_FIR_IO_BASEADDR
	},
	{
		XPAR_FIR_1_DEVICE_ID,
		XPAR_FIR_1_S_AXI_FIR_IO_BASEADDR
	}
};


