# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Education/FPGA_Labs/Lab3/Lab3.srcs/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_bram_ctrl_0_0/Lab2_Block_Design_axi_bram_ctrl_0_0.xci
# IP: The module: 'Lab2_Block_Design_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Education/FPGA_Labs/Lab3/Lab3.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_bram_ctrl_0_0/Lab2_Block_Design_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab3/Lab3.srcs/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_bram_ctrl_0_0/Lab2_Block_Design_axi_bram_ctrl_0_0.xci
# IP: The module: 'Lab2_Block_Design_axi_bram_ctrl_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Education/FPGA_Labs/Lab3/Lab3.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_bram_ctrl_0_0/Lab2_Block_Design_axi_bram_ctrl_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_axi_bram_ctrl_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
