# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.srcs/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/Lab2_Block_Design_axi_gpio_0_2.xci
# IP: The module: 'Lab2_Block_Design_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/Lab2_Block_Design_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/Lab2_Block_Design_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/Lab2_Block_Design_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.srcs/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/Lab2_Block_Design_axi_gpio_0_2.xci
# IP: The module: 'Lab2_Block_Design_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/Lab2_Block_Design_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/Lab2_Block_Design_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/Lab2_Block_Design_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
