// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="dct_dct,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.508000,HLS_SYN_LAT=2450,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=515,HLS_SYN_LUT=1549,HLS_VERSION=2023_1}" *)

module dct (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] input_r_address0;
output   input_r_ce0;
input  [15:0] input_r_q0;
output  [5:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [15:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [5:0] dct_coeff_table_address0;
reg    dct_coeff_table_ce0;
wire   [14:0] dct_coeff_table_q0;
wire   [0:0] icmp_ln39_fu_241_p2;
reg   [0:0] icmp_ln39_reg_522;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln58_fu_217_p2;
wire   [2:0] trunc_ln45_fu_255_p1;
reg   [2:0] trunc_ln45_reg_527;
wire   [5:0] tmp_5_fu_294_p3;
reg   [5:0] tmp_5_reg_553;
wire    ap_CS_fsm_state4;
wire   [5:0] tmp_6_fu_306_p3;
reg   [5:0] tmp_6_reg_558;
wire   [5:0] add_ln45_2_fu_315_p2;
reg   [5:0] add_ln45_2_reg_563;
wire   [0:0] icmp_ln39_1_fu_383_p2;
reg   [0:0] icmp_ln39_1_reg_574;
wire    ap_CS_fsm_state8;
wire   [0:0] icmp_ln69_fu_359_p2;
wire   [2:0] trunc_ln45_2_fu_397_p1;
reg   [2:0] trunc_ln45_2_reg_579;
wire   [5:0] tmp_s_fu_421_p3;
reg   [5:0] tmp_s_reg_584;
wire    ap_CS_fsm_state9;
wire   [5:0] tmp_2_fu_433_p3;
reg   [5:0] tmp_2_reg_589;
wire   [5:0] add_ln45_3_fu_442_p2;
reg   [5:0] add_ln45_3_reg_594;
reg   [5:0] row_outbuf_address0;
reg    row_outbuf_ce0;
reg    row_outbuf_we0;
wire   [15:0] row_outbuf_d0;
wire   [15:0] row_outbuf_q0;
reg   [5:0] col_outbuf_address0;
reg    col_outbuf_ce0;
reg    col_outbuf_we0;
wire   [15:0] col_outbuf_d0;
wire   [15:0] col_outbuf_q0;
reg   [5:0] col_inbuf_address0;
reg    col_inbuf_ce0;
reg    col_inbuf_we0;
wire   [15:0] col_inbuf_q0;
reg   [5:0] buf_2d_in_address0;
reg    buf_2d_in_ce0;
reg    buf_2d_in_we0;
wire   [15:0] buf_2d_in_q0;
reg   [5:0] buf_2d_out_address0;
reg    buf_2d_out_ce0;
reg    buf_2d_out_we0;
wire   [15:0] buf_2d_out_q0;
wire    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start;
wire    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_done;
wire    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_idle;
wire    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_ready;
wire   [5:0] grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_address0;
wire    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_ce0;
wire    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_we0;
wire   [15:0] grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_d0;
wire   [5:0] grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_input_r_address0;
wire    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_input_r_ce0;
wire    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start;
wire    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_done;
wire    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_idle;
wire    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_ready;
wire   [5:0] grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_row_outbuf_address0;
wire    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_row_outbuf_ce0;
wire   [5:0] grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_address0;
wire    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_ce0;
wire    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_we0;
wire   [15:0] grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_d0;
wire    grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start;
wire    grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_done;
wire    grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_idle;
wire    grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_ready;
wire   [5:0] grp_dct_Pipeline_DCT_Inner_Loop_fu_166_buf_2d_in_address0;
wire    grp_dct_Pipeline_DCT_Inner_Loop_fu_166_buf_2d_in_ce0;
wire   [28:0] grp_dct_Pipeline_DCT_Inner_Loop_fu_166_tmp_out;
wire    grp_dct_Pipeline_DCT_Inner_Loop_fu_166_tmp_out_ap_vld;
wire   [5:0] grp_dct_Pipeline_DCT_Inner_Loop_fu_166_dct_coeff_table_address0;
wire    grp_dct_Pipeline_DCT_Inner_Loop_fu_166_dct_coeff_table_ce0;
wire    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start;
wire    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_done;
wire    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_idle;
wire    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_ready;
wire   [5:0] grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_col_outbuf_address0;
wire    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_col_outbuf_ce0;
wire   [5:0] grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_address0;
wire    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_ce0;
wire    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_we0;
wire   [15:0] grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_d0;
wire    grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start;
wire    grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_done;
wire    grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_idle;
wire    grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_ready;
wire   [5:0] grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_col_inbuf_address0;
wire    grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_col_inbuf_ce0;
wire   [28:0] grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_tmp_2_out;
wire    grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_tmp_2_out_ap_vld;
wire   [5:0] grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_dct_coeff_table_address0;
wire    grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_dct_coeff_table_ce0;
wire    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start;
wire    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_done;
wire    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_idle;
wire    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_ready;
wire   [5:0] grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_buf_2d_out_address0;
wire    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_buf_2d_out_ce0;
wire   [5:0] grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_address0;
wire    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_ce0;
wire    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_we0;
wire   [15:0] grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_d0;
reg    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start_reg;
wire    ap_CS_fsm_state7;
reg    grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start_reg;
wire    ap_CS_fsm_state5;
reg   [28:0] tmp_loc_fu_92;
reg    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start_reg;
wire    ap_CS_fsm_state10;
reg   [28:0] tmp_2_loc_fu_88;
reg    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire   [63:0] zext_ln45_fu_332_p1;
wire    ap_CS_fsm_state6;
wire   [63:0] zext_ln45_1_fu_459_p1;
wire    ap_CS_fsm_state11;
reg   [3:0] k_fu_76;
wire   [3:0] add_ln39_fu_321_p2;
reg   [3:0] i_fu_80;
wire   [3:0] select_ln58_1_fu_247_p3;
reg   [6:0] indvar_flatten6_fu_84;
wire   [6:0] add_ln58_1_fu_223_p2;
reg   [3:0] k_1_fu_116;
wire   [3:0] add_ln39_1_fu_448_p2;
reg   [3:0] i_1_fu_120;
wire   [3:0] select_ln69_1_fu_389_p3;
reg   [6:0] indvar_flatten20_fu_124;
wire   [6:0] add_ln69_1_fu_365_p2;
wire   [3:0] add_ln58_fu_235_p2;
wire   [3:0] select_ln58_fu_284_p3;
wire   [2:0] trunc_ln58_fu_290_p1;
wire   [5:0] zext_ln42_fu_302_p1;
wire   [28:0] add_ln45_fu_339_p2;
wire   [3:0] add_ln69_fu_377_p2;
wire   [3:0] select_ln69_fu_411_p3;
wire   [2:0] trunc_ln69_fu_417_p1;
wire   [5:0] zext_ln42_5_fu_429_p1;
wire   [28:0] add_ln45_1_fu_466_p2;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start_reg = 1'b0;
#0 grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start_reg = 1'b0;
#0 grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start_reg = 1'b0;
#0 grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start_reg = 1'b0;
#0 grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start_reg = 1'b0;
#0 grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start_reg = 1'b0;
end

dct_dct_coeff_table_ROM_AUTO_1R #(
    .DataWidth( 15 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
dct_coeff_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(dct_coeff_table_address0),
    .ce0(dct_coeff_table_ce0),
    .q0(dct_coeff_table_q0)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
row_outbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(row_outbuf_address0),
    .ce0(row_outbuf_ce0),
    .we0(row_outbuf_we0),
    .d0(row_outbuf_d0),
    .q0(row_outbuf_q0)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
col_outbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_outbuf_address0),
    .ce0(col_outbuf_ce0),
    .we0(col_outbuf_we0),
    .d0(col_outbuf_d0),
    .q0(col_outbuf_q0)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
col_inbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_address0),
    .ce0(col_inbuf_ce0),
    .we0(col_inbuf_we0),
    .d0(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_d0),
    .q0(col_inbuf_q0)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_2d_in_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2d_in_address0),
    .ce0(buf_2d_in_ce0),
    .we0(buf_2d_in_we0),
    .d0(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_d0),
    .q0(buf_2d_in_q0)
);

dct_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
buf_2d_out_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2d_out_address0),
    .ce0(buf_2d_out_ce0),
    .we0(buf_2d_out_we0),
    .d0(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_d0),
    .q0(buf_2d_out_q0)
);

dct_dct_Pipeline_RD_Loop_Row_RD_Loop_Col grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start),
    .ap_done(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_done),
    .ap_idle(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_idle),
    .ap_ready(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_ready),
    .buf_2d_in_address0(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_address0),
    .buf_2d_in_ce0(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_ce0),
    .buf_2d_in_we0(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_we0),
    .buf_2d_in_d0(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_d0),
    .input_r_address0(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_input_r_address0),
    .input_r_ce0(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_input_r_ce0),
    .input_r_q0(input_r_q0)
);

dct_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start),
    .ap_done(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_done),
    .ap_idle(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_idle),
    .ap_ready(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_ready),
    .row_outbuf_address0(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_row_outbuf_address0),
    .row_outbuf_ce0(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_row_outbuf_ce0),
    .row_outbuf_q0(row_outbuf_q0),
    .col_inbuf_address0(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_address0),
    .col_inbuf_ce0(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_ce0),
    .col_inbuf_we0(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_we0),
    .col_inbuf_d0(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_d0)
);

dct_dct_Pipeline_DCT_Inner_Loop grp_dct_Pipeline_DCT_Inner_Loop_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start),
    .ap_done(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_done),
    .ap_idle(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_idle),
    .ap_ready(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_ready),
    .zext_ln42(tmp_6_reg_558),
    .zext_ln45(tmp_5_reg_553),
    .buf_2d_in_address0(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_buf_2d_in_address0),
    .buf_2d_in_ce0(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_buf_2d_in_ce0),
    .buf_2d_in_q0(buf_2d_in_q0),
    .tmp_out(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_tmp_out),
    .tmp_out_ap_vld(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_tmp_out_ap_vld),
    .dct_coeff_table_address0(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_dct_coeff_table_address0),
    .dct_coeff_table_ce0(grp_dct_Pipeline_DCT_Inner_Loop_fu_166_dct_coeff_table_ce0),
    .dct_coeff_table_q0(dct_coeff_table_q0)
);

dct_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start),
    .ap_done(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_done),
    .ap_idle(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_idle),
    .ap_ready(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_ready),
    .col_outbuf_address0(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_col_outbuf_address0),
    .col_outbuf_ce0(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_col_outbuf_ce0),
    .col_outbuf_q0(col_outbuf_q0),
    .buf_2d_out_address0(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_address0),
    .buf_2d_out_ce0(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_ce0),
    .buf_2d_out_we0(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_we0),
    .buf_2d_out_d0(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_d0)
);

dct_dct_Pipeline_DCT_Inner_Loop1 grp_dct_Pipeline_DCT_Inner_Loop1_fu_182(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start),
    .ap_done(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_done),
    .ap_idle(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_idle),
    .ap_ready(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_ready),
    .zext_ln42_1(tmp_2_reg_589),
    .zext_ln45_1(tmp_s_reg_584),
    .col_inbuf_address0(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_col_inbuf_address0),
    .col_inbuf_ce0(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_col_inbuf_ce0),
    .col_inbuf_q0(col_inbuf_q0),
    .tmp_2_out(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_tmp_2_out),
    .tmp_2_out_ap_vld(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_tmp_2_out_ap_vld),
    .dct_coeff_table_address0(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_dct_coeff_table_address0),
    .dct_coeff_table_ce0(grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_dct_coeff_table_ce0),
    .dct_coeff_table_q0(dct_coeff_table_q0)
);

dct_dct_Pipeline_WR_Loop_Row_WR_Loop_Col grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start),
    .ap_done(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_done),
    .ap_idle(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_idle),
    .ap_ready(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_ready),
    .buf_2d_out_address0(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_buf_2d_out_address0),
    .buf_2d_out_ce0(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_buf_2d_out_ce0),
    .buf_2d_out_q0(buf_2d_out_q0),
    .output_r_address0(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_address0),
    .output_r_ce0(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_ce0),
    .output_r_we0(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_we0),
    .output_r_d0(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_d0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start_reg <= 1'b1;
        end else if ((grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_ready == 1'b1)) begin
            grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state4)) begin
            grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start_reg <= 1'b1;
        end else if ((grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_ready == 1'b1)) begin
            grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start_reg <= 1'b1;
        end else if ((grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_ready == 1'b1)) begin
            grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start_reg <= 1'b1;
        end else if ((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_ready == 1'b1)) begin
            grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln69_fu_359_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
            grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start_reg <= 1'b1;
        end else if ((grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_ready == 1'b1)) begin
            grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln58_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_ready == 1'b1)) begin
            grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln58_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        i_1_fu_120 <= 4'd0;
    end else if (((icmp_ln69_fu_359_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        i_1_fu_120 <= select_ln69_1_fu_389_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_fu_80 <= 4'd0;
    end else if (((icmp_ln58_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_fu_80 <= select_ln58_1_fu_247_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln58_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten20_fu_124 <= 7'd0;
    end else if (((icmp_ln69_fu_359_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        indvar_flatten20_fu_124 <= add_ln69_1_fu_365_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten6_fu_84 <= 7'd0;
    end else if (((icmp_ln58_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        indvar_flatten6_fu_84 <= add_ln58_1_fu_223_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln58_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        k_1_fu_116 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        k_1_fu_116 <= add_ln39_1_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        k_fu_76 <= 4'd0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        k_fu_76 <= add_ln39_fu_321_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln45_2_reg_563 <= add_ln45_2_fu_315_p2;
        tmp_5_reg_553[5 : 3] <= tmp_5_fu_294_p3[5 : 3];
        tmp_6_reg_558[5 : 3] <= tmp_6_fu_306_p3[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        add_ln45_3_reg_594 <= add_ln45_3_fu_442_p2;
        tmp_2_reg_589[5 : 3] <= tmp_2_fu_433_p3[5 : 3];
        tmp_s_reg_584[5 : 3] <= tmp_s_fu_421_p3[5 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln69_fu_359_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state8))) begin
        icmp_ln39_1_reg_574 <= icmp_ln39_1_fu_383_p2;
        trunc_ln45_2_reg_579 <= trunc_ln45_2_fu_397_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln58_fu_217_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_ln39_reg_522 <= icmp_ln39_fu_241_p2;
        trunc_ln45_reg_527 <= trunc_ln45_fu_255_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_tmp_2_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        tmp_2_loc_fu_88 <= grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_tmp_2_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) & (grp_dct_Pipeline_DCT_Inner_Loop_fu_166_tmp_out_ap_vld == 1'b1))) begin
        tmp_loc_fu_92 <= grp_dct_Pipeline_DCT_Inner_Loop_fu_166_tmp_out;
    end
end

always @ (*) begin
    if ((grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_in_address0 = grp_dct_Pipeline_DCT_Inner_Loop_fu_166_buf_2d_in_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_2d_in_address0 = grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_address0;
    end else begin
        buf_2d_in_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_2d_in_ce0 = grp_dct_Pipeline_DCT_Inner_Loop_fu_166_buf_2d_in_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_2d_in_ce0 = grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_ce0;
    end else begin
        buf_2d_in_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        buf_2d_in_we0 = grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_buf_2d_in_we0;
    end else begin
        buf_2d_in_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buf_2d_out_address0 = grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_buf_2d_out_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_2d_out_address0 = grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_address0;
    end else begin
        buf_2d_out_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        buf_2d_out_ce0 = grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_buf_2d_out_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_2d_out_ce0 = grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_ce0;
    end else begin
        buf_2d_out_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        buf_2d_out_we0 = grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_buf_2d_out_we0;
    end else begin
        buf_2d_out_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        col_inbuf_address0 = grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_col_inbuf_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        col_inbuf_address0 = grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_address0;
    end else begin
        col_inbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        col_inbuf_ce0 = grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_col_inbuf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        col_inbuf_ce0 = grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_ce0;
    end else begin
        col_inbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        col_inbuf_we0 = grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_col_inbuf_we0;
    end else begin
        col_inbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        col_outbuf_address0 = zext_ln45_1_fu_459_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        col_outbuf_address0 = grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_col_outbuf_address0;
    end else begin
        col_outbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        col_outbuf_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        col_outbuf_ce0 = grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_col_outbuf_ce0;
    end else begin
        col_outbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        col_outbuf_we0 = 1'b1;
    end else begin
        col_outbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        dct_coeff_table_address0 = grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_dct_coeff_table_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dct_coeff_table_address0 = grp_dct_Pipeline_DCT_Inner_Loop_fu_166_dct_coeff_table_address0;
    end else begin
        dct_coeff_table_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        dct_coeff_table_ce0 = grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_dct_coeff_table_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        dct_coeff_table_ce0 = grp_dct_Pipeline_DCT_Inner_Loop_fu_166_dct_coeff_table_ce0;
    end else begin
        dct_coeff_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_outbuf_address0 = zext_ln45_fu_332_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        row_outbuf_address0 = grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_row_outbuf_address0;
    end else begin
        row_outbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_outbuf_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        row_outbuf_ce0 = grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_row_outbuf_ce0;
    end else begin
        row_outbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        row_outbuf_we0 = 1'b1;
    end else begin
        row_outbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln58_fu_217_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_CS_fsm_state5) & (grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((icmp_ln69_fu_359_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln39_1_fu_448_p2 = (select_ln69_fu_411_p3 + 4'd1);

assign add_ln39_fu_321_p2 = (select_ln58_fu_284_p3 + 4'd1);

assign add_ln45_1_fu_466_p2 = (tmp_2_loc_fu_88 + 29'd4096);

assign add_ln45_2_fu_315_p2 = (tmp_5_fu_294_p3 + zext_ln42_fu_302_p1);

assign add_ln45_3_fu_442_p2 = (tmp_s_fu_421_p3 + zext_ln42_5_fu_429_p1);

assign add_ln45_fu_339_p2 = (tmp_loc_fu_92 + 29'd4096);

assign add_ln58_1_fu_223_p2 = (indvar_flatten6_fu_84 + 7'd1);

assign add_ln58_fu_235_p2 = (i_fu_80 + 4'd1);

assign add_ln69_1_fu_365_p2 = (indvar_flatten20_fu_124 + 7'd1);

assign add_ln69_fu_377_p2 = (i_1_fu_120 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign col_outbuf_d0 = {{add_ln45_1_fu_466_p2[28:13]}};

assign grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start = grp_dct_Pipeline_DCT_Inner_Loop1_fu_182_ap_start_reg;

assign grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start = grp_dct_Pipeline_DCT_Inner_Loop_fu_166_ap_start_reg;

assign grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start = grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_ap_start_reg;

assign grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start = grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_ap_start_reg;

assign grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start = grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_176_ap_start_reg;

assign grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start = grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_160_ap_start_reg;

assign icmp_ln39_1_fu_383_p2 = ((k_1_fu_116 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_241_p2 = ((k_fu_76 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_217_p2 = ((indvar_flatten6_fu_84 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_359_p2 = ((indvar_flatten20_fu_124 == 7'd64) ? 1'b1 : 1'b0);

assign input_r_address0 = grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_input_r_address0;

assign input_r_ce0 = grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_152_input_r_ce0;

assign output_r_address0 = grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_address0;

assign output_r_ce0 = grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_ce0;

assign output_r_d0 = grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_d0;

assign output_r_we0 = grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_192_output_r_we0;

assign row_outbuf_d0 = {{add_ln45_fu_339_p2[28:13]}};

assign select_ln58_1_fu_247_p3 = ((icmp_ln39_fu_241_p2[0:0] == 1'b1) ? add_ln58_fu_235_p2 : i_fu_80);

assign select_ln58_fu_284_p3 = ((icmp_ln39_reg_522[0:0] == 1'b1) ? 4'd0 : k_fu_76);

assign select_ln69_1_fu_389_p3 = ((icmp_ln39_1_fu_383_p2[0:0] == 1'b1) ? add_ln69_fu_377_p2 : i_1_fu_120);

assign select_ln69_fu_411_p3 = ((icmp_ln39_1_reg_574[0:0] == 1'b1) ? 4'd0 : k_1_fu_116);

assign tmp_2_fu_433_p3 = {{trunc_ln69_fu_417_p1}, {3'd0}};

assign tmp_5_fu_294_p3 = {{trunc_ln45_reg_527}, {3'd0}};

assign tmp_6_fu_306_p3 = {{trunc_ln58_fu_290_p1}, {3'd0}};

assign tmp_s_fu_421_p3 = {{trunc_ln45_2_reg_579}, {3'd0}};

assign trunc_ln45_2_fu_397_p1 = select_ln69_1_fu_389_p3[2:0];

assign trunc_ln45_fu_255_p1 = select_ln58_1_fu_247_p3[2:0];

assign trunc_ln58_fu_290_p1 = select_ln58_fu_284_p3[2:0];

assign trunc_ln69_fu_417_p1 = select_ln69_fu_411_p3[2:0];

assign zext_ln42_5_fu_429_p1 = select_ln69_fu_411_p3;

assign zext_ln42_fu_302_p1 = select_ln58_fu_284_p3;

assign zext_ln45_1_fu_459_p1 = add_ln45_3_reg_594;

assign zext_ln45_fu_332_p1 = add_ln45_2_reg_563;

always @ (posedge ap_clk) begin
    tmp_5_reg_553[2:0] <= 3'b000;
    tmp_6_reg_558[2:0] <= 3'b000;
    tmp_s_reg_584[2:0] <= 3'b000;
    tmp_2_reg_589[2:0] <= 3'b000;
end

endmodule //dct
