# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Education/FPGA_Labs/Labs_2/lab4/audio_new/audio_new.srcs/sources_1/bd/design_1/ip/design_1_fir_0_4/design_1_fir_0_4.xci
# IP: The module: 'design_1_fir_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Education/FPGA_Labs/Labs_2/lab4/audio_new/audio_new.gen/sources_1/bd/design_1/ip/design_1_fir_0_4/constraints/fir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_0_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Labs_2/lab4/audio_new/audio_new.srcs/sources_1/bd/design_1/ip/design_1_fir_0_4/design_1_fir_0_4.xci
# IP: The module: 'design_1_fir_0_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Education/FPGA_Labs/Labs_2/lab4/audio_new/audio_new.gen/sources_1/bd/design_1/ip/design_1_fir_0_4/constraints/fir_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fir_0_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
