// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module dct_dct_2d (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_block_0_address0,
        in_block_0_ce0,
        in_block_0_q0,
        in_block_1_address0,
        in_block_1_ce0,
        in_block_1_q0,
        in_block_2_address0,
        in_block_2_ce0,
        in_block_2_q0,
        in_block_3_address0,
        in_block_3_ce0,
        in_block_3_q0,
        in_block_4_address0,
        in_block_4_ce0,
        in_block_4_q0,
        in_block_5_address0,
        in_block_5_ce0,
        in_block_5_q0,
        in_block_6_address0,
        in_block_6_ce0,
        in_block_6_q0,
        in_block_7_address0,
        in_block_7_ce0,
        in_block_7_q0,
        out_block_address0,
        out_block_ce0,
        out_block_we0,
        out_block_d0
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [2:0] in_block_0_address0;
output   in_block_0_ce0;
input  [15:0] in_block_0_q0;
output  [2:0] in_block_1_address0;
output   in_block_1_ce0;
input  [15:0] in_block_1_q0;
output  [2:0] in_block_2_address0;
output   in_block_2_ce0;
input  [15:0] in_block_2_q0;
output  [2:0] in_block_3_address0;
output   in_block_3_ce0;
input  [15:0] in_block_3_q0;
output  [2:0] in_block_4_address0;
output   in_block_4_ce0;
input  [15:0] in_block_4_q0;
output  [2:0] in_block_5_address0;
output   in_block_5_ce0;
input  [15:0] in_block_5_q0;
output  [2:0] in_block_6_address0;
output   in_block_6_ce0;
input  [15:0] in_block_6_q0;
output  [2:0] in_block_7_address0;
output   in_block_7_ce0;
input  [15:0] in_block_7_q0;
output  [5:0] out_block_address0;
output   out_block_ce0;
output   out_block_we0;
output  [15:0] out_block_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_block_0_ce0;
reg in_block_1_ce0;
reg in_block_2_ce0;
reg in_block_3_ce0;
reg in_block_4_ce0;
reg in_block_5_ce0;
reg in_block_6_ce0;
reg in_block_7_ce0;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [2:0] trunc_ln58_fu_396_p1;
reg   [2:0] trunc_ln58_reg_465;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln58_fu_400_p2;
reg   [15:0] in_block_0_load_reg_520;
wire    ap_CS_fsm_state3;
reg   [15:0] in_block_1_load_reg_525;
reg   [15:0] in_block_2_load_reg_530;
reg   [15:0] in_block_3_load_reg_535;
reg   [15:0] in_block_4_load_reg_540;
reg   [15:0] in_block_5_load_reg_545;
reg   [15:0] in_block_6_load_reg_550;
reg   [15:0] in_block_7_load_reg_555;
wire   [2:0] trunc_ln69_fu_437_p1;
reg   [2:0] trunc_ln69_reg_560;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln69_fu_441_p2;
wire   [15:0] col_inbuf_q0;
reg   [15:0] col_inbuf_load_reg_608;
wire    ap_CS_fsm_state7;
wire   [15:0] col_inbuf_1_q0;
reg   [15:0] col_inbuf_1_load_reg_613;
wire   [15:0] col_inbuf_2_q0;
reg   [15:0] col_inbuf_2_load_reg_618;
wire   [15:0] col_inbuf_3_q0;
reg   [15:0] col_inbuf_3_load_reg_623;
wire   [15:0] col_inbuf_4_q0;
reg   [15:0] col_inbuf_4_load_reg_628;
wire   [15:0] col_inbuf_5_q0;
reg   [15:0] col_inbuf_5_load_reg_633;
wire   [15:0] col_inbuf_6_q0;
reg   [15:0] col_inbuf_6_load_reg_638;
wire   [15:0] col_inbuf_7_q0;
reg   [15:0] col_inbuf_7_load_reg_643;
reg   [5:0] row_outbuf_address0;
reg    row_outbuf_ce0;
reg    row_outbuf_we0;
wire   [15:0] row_outbuf_q0;
reg   [5:0] col_outbuf_address0;
reg    col_outbuf_ce0;
reg    col_outbuf_we0;
wire   [15:0] col_outbuf_q0;
reg   [2:0] col_inbuf_address0;
reg    col_inbuf_ce0;
reg    col_inbuf_we0;
reg   [2:0] col_inbuf_1_address0;
reg    col_inbuf_1_ce0;
reg    col_inbuf_1_we0;
reg   [2:0] col_inbuf_2_address0;
reg    col_inbuf_2_ce0;
reg    col_inbuf_2_we0;
reg   [2:0] col_inbuf_3_address0;
reg    col_inbuf_3_ce0;
reg    col_inbuf_3_we0;
reg   [2:0] col_inbuf_4_address0;
reg    col_inbuf_4_ce0;
reg    col_inbuf_4_we0;
reg   [2:0] col_inbuf_5_address0;
reg    col_inbuf_5_ce0;
reg    col_inbuf_5_we0;
reg   [2:0] col_inbuf_6_address0;
reg    col_inbuf_6_ce0;
reg    col_inbuf_6_we0;
reg   [2:0] col_inbuf_7_address0;
reg    col_inbuf_7_ce0;
reg    col_inbuf_7_we0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_done;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_idle;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_ready;
wire   [2:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_d0;
wire   [5:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_row_outbuf_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_row_outbuf_ce0;
wire   [2:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_d0;
wire   [2:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_d0;
wire   [2:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_d0;
wire   [2:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_d0;
wire   [2:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_d0;
wire   [2:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_d0;
wire   [2:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_address0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_d0;
wire    grp_dct_1d_6_7_fu_323_ap_start;
wire    grp_dct_1d_6_7_fu_323_ap_done;
wire    grp_dct_1d_6_7_fu_323_ap_idle;
wire    grp_dct_1d_6_7_fu_323_ap_ready;
reg   [15:0] grp_dct_1d_6_7_fu_323_src_0_val;
reg   [15:0] grp_dct_1d_6_7_fu_323_src_1_val;
reg   [15:0] grp_dct_1d_6_7_fu_323_src_2_val;
reg   [15:0] grp_dct_1d_6_7_fu_323_src_3_val;
reg   [15:0] grp_dct_1d_6_7_fu_323_src_4_val;
reg   [15:0] grp_dct_1d_6_7_fu_323_src_5_val;
reg   [15:0] grp_dct_1d_6_7_fu_323_src_6_val;
reg   [15:0] grp_dct_1d_6_7_fu_323_src_7_val;
wire   [5:0] grp_dct_1d_6_7_fu_323_dst_address0;
wire    grp_dct_1d_6_7_fu_323_dst_ce0;
wire    grp_dct_1d_6_7_fu_323_dst_we0;
wire   [15:0] grp_dct_1d_6_7_fu_323_dst_d0;
reg   [2:0] grp_dct_1d_6_7_fu_323_dst_offset;
wire    grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start;
wire    grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_done;
wire    grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_idle;
wire    grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_ready;
wire   [5:0] grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_address0;
wire    grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_ce0;
wire    grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_we0;
wire   [15:0] grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_d0;
wire   [5:0] grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_col_outbuf_address0;
wire    grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_col_outbuf_ce0;
reg    grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start_reg;
wire    ap_CS_fsm_state5;
reg    grp_dct_1d_6_7_fu_323_ap_start_reg;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state8;
reg    grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start_reg;
wire    ap_CS_fsm_state9;
wire   [63:0] zext_ln58_fu_384_p1;
wire   [63:0] zext_ln69_fu_425_p1;
reg   [3:0] i_fu_62;
wire   [3:0] add_ln58_fu_406_p2;
reg    ap_block_state1;
reg   [3:0] i_1_fu_106;
wire   [3:0] add_ln69_fu_447_p2;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
reg    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 9'd1;
#0 grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start_reg = 1'b0;
#0 grp_dct_1d_6_7_fu_323_ap_start_reg = 1'b0;
#0 grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start_reg = 1'b0;
end

dct_dct_2d_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
row_outbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(row_outbuf_address0),
    .ce0(row_outbuf_ce0),
    .we0(row_outbuf_we0),
    .d0(grp_dct_1d_6_7_fu_323_dst_d0),
    .q0(row_outbuf_q0)
);

dct_dct_2d_row_outbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
col_outbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_outbuf_address0),
    .ce0(col_outbuf_ce0),
    .we0(col_outbuf_we0),
    .d0(grp_dct_1d_6_7_fu_323_dst_d0),
    .q0(col_outbuf_q0)
);

dct_dct_2d_col_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_address0),
    .ce0(col_inbuf_ce0),
    .we0(col_inbuf_we0),
    .d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_d0),
    .q0(col_inbuf_q0)
);

dct_dct_2d_col_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_1_address0),
    .ce0(col_inbuf_1_ce0),
    .we0(col_inbuf_1_we0),
    .d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_d0),
    .q0(col_inbuf_1_q0)
);

dct_dct_2d_col_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_2_address0),
    .ce0(col_inbuf_2_ce0),
    .we0(col_inbuf_2_we0),
    .d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_d0),
    .q0(col_inbuf_2_q0)
);

dct_dct_2d_col_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_3_address0),
    .ce0(col_inbuf_3_ce0),
    .we0(col_inbuf_3_we0),
    .d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_d0),
    .q0(col_inbuf_3_q0)
);

dct_dct_2d_col_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_4_address0),
    .ce0(col_inbuf_4_ce0),
    .we0(col_inbuf_4_we0),
    .d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_d0),
    .q0(col_inbuf_4_q0)
);

dct_dct_2d_col_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_5_address0),
    .ce0(col_inbuf_5_ce0),
    .we0(col_inbuf_5_we0),
    .d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_d0),
    .q0(col_inbuf_5_q0)
);

dct_dct_2d_col_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_6_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_6_address0),
    .ce0(col_inbuf_6_ce0),
    .we0(col_inbuf_6_we0),
    .d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_d0),
    .q0(col_inbuf_6_q0)
);

dct_dct_2d_col_inbuf_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
col_inbuf_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(col_inbuf_7_address0),
    .ce0(col_inbuf_7_ce0),
    .we0(col_inbuf_7_we0),
    .d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_d0),
    .q0(col_inbuf_7_q0)
);

dct_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start),
    .ap_done(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_done),
    .ap_idle(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_idle),
    .ap_ready(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_ready),
    .col_inbuf_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_address0),
    .col_inbuf_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_ce0),
    .col_inbuf_we0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_we0),
    .col_inbuf_d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_d0),
    .row_outbuf_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_row_outbuf_address0),
    .row_outbuf_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_row_outbuf_ce0),
    .row_outbuf_q0(row_outbuf_q0),
    .col_inbuf_7_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_address0),
    .col_inbuf_7_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_ce0),
    .col_inbuf_7_we0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_we0),
    .col_inbuf_7_d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_d0),
    .col_inbuf_6_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_address0),
    .col_inbuf_6_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_ce0),
    .col_inbuf_6_we0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_we0),
    .col_inbuf_6_d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_d0),
    .col_inbuf_5_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_address0),
    .col_inbuf_5_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_ce0),
    .col_inbuf_5_we0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_we0),
    .col_inbuf_5_d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_d0),
    .col_inbuf_4_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_address0),
    .col_inbuf_4_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_ce0),
    .col_inbuf_4_we0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_we0),
    .col_inbuf_4_d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_d0),
    .col_inbuf_3_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_address0),
    .col_inbuf_3_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_ce0),
    .col_inbuf_3_we0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_we0),
    .col_inbuf_3_d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_d0),
    .col_inbuf_2_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_address0),
    .col_inbuf_2_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_ce0),
    .col_inbuf_2_we0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_we0),
    .col_inbuf_2_d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_d0),
    .col_inbuf_1_address0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_address0),
    .col_inbuf_1_ce0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_ce0),
    .col_inbuf_1_we0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_we0),
    .col_inbuf_1_d0(grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_d0)
);

dct_dct_1d_6_7 grp_dct_1d_6_7_fu_323(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_1d_6_7_fu_323_ap_start),
    .ap_done(grp_dct_1d_6_7_fu_323_ap_done),
    .ap_idle(grp_dct_1d_6_7_fu_323_ap_idle),
    .ap_ready(grp_dct_1d_6_7_fu_323_ap_ready),
    .src_0_val(grp_dct_1d_6_7_fu_323_src_0_val),
    .src_1_val(grp_dct_1d_6_7_fu_323_src_1_val),
    .src_2_val(grp_dct_1d_6_7_fu_323_src_2_val),
    .src_3_val(grp_dct_1d_6_7_fu_323_src_3_val),
    .src_4_val(grp_dct_1d_6_7_fu_323_src_4_val),
    .src_5_val(grp_dct_1d_6_7_fu_323_src_5_val),
    .src_6_val(grp_dct_1d_6_7_fu_323_src_6_val),
    .src_7_val(grp_dct_1d_6_7_fu_323_src_7_val),
    .dst_address0(grp_dct_1d_6_7_fu_323_dst_address0),
    .dst_ce0(grp_dct_1d_6_7_fu_323_dst_ce0),
    .dst_we0(grp_dct_1d_6_7_fu_323_dst_we0),
    .dst_d0(grp_dct_1d_6_7_fu_323_dst_d0),
    .dst_offset(grp_dct_1d_6_7_fu_323_dst_offset)
);

dct_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start),
    .ap_done(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_done),
    .ap_idle(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_idle),
    .ap_ready(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_ready),
    .out_block_address0(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_address0),
    .out_block_ce0(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_ce0),
    .out_block_we0(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_we0),
    .out_block_d0(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_d0),
    .col_outbuf_address0(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_col_outbuf_address0),
    .col_outbuf_ce0(grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_col_outbuf_ce0),
    .col_outbuf_q0(col_outbuf_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_1d_6_7_fu_323_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state3))) begin
            grp_dct_1d_6_7_fu_323_ap_start_reg <= 1'b1;
        end else if ((grp_dct_1d_6_7_fu_323_ap_ready == 1'b1)) begin
            grp_dct_1d_6_7_fu_323_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln69_fu_441_p2 == 1'd1))) begin
            grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start_reg <= 1'b1;
        end else if ((grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_ready == 1'b1)) begin
            grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln58_fu_400_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start_reg <= 1'b1;
        end else if ((grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_ready == 1'b1)) begin
            grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln58_fu_400_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        i_1_fu_106 <= 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln69_fu_441_p2 == 1'd0))) begin
        i_1_fu_106 <= add_ln69_fu_447_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_62 <= 4'd0;
    end else if (((icmp_ln58_fu_400_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_62 <= add_ln58_fu_406_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        col_inbuf_1_load_reg_613 <= col_inbuf_1_q0;
        col_inbuf_2_load_reg_618 <= col_inbuf_2_q0;
        col_inbuf_3_load_reg_623 <= col_inbuf_3_q0;
        col_inbuf_4_load_reg_628 <= col_inbuf_4_q0;
        col_inbuf_5_load_reg_633 <= col_inbuf_5_q0;
        col_inbuf_6_load_reg_638 <= col_inbuf_6_q0;
        col_inbuf_7_load_reg_643 <= col_inbuf_7_q0;
        col_inbuf_load_reg_608 <= col_inbuf_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_block_0_load_reg_520 <= in_block_0_q0;
        in_block_1_load_reg_525 <= in_block_1_q0;
        in_block_2_load_reg_530 <= in_block_2_q0;
        in_block_3_load_reg_535 <= in_block_3_q0;
        in_block_4_load_reg_540 <= in_block_4_q0;
        in_block_5_load_reg_545 <= in_block_5_q0;
        in_block_6_load_reg_550 <= in_block_6_q0;
        in_block_7_load_reg_555 <= in_block_7_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln58_reg_465 <= trunc_ln58_fu_396_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        trunc_ln69_reg_560 <= trunc_ln69_fu_437_p1;
    end
end

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_dct_1d_6_7_fu_323_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_done == 1'b0)) begin
        ap_ST_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_fsm_state5_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_dct_1d_6_7_fu_323_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_1_address0 = zext_ln69_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_1_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_address0;
    end else begin
        col_inbuf_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_1_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_1_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_ce0;
    end else begin
        col_inbuf_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_1_we0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_1_we0;
    end else begin
        col_inbuf_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_2_address0 = zext_ln69_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_2_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_address0;
    end else begin
        col_inbuf_2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_2_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_2_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_ce0;
    end else begin
        col_inbuf_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_2_we0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_2_we0;
    end else begin
        col_inbuf_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_3_address0 = zext_ln69_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_3_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_address0;
    end else begin
        col_inbuf_3_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_3_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_3_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_ce0;
    end else begin
        col_inbuf_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_3_we0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_3_we0;
    end else begin
        col_inbuf_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_4_address0 = zext_ln69_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_4_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_address0;
    end else begin
        col_inbuf_4_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_4_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_4_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_ce0;
    end else begin
        col_inbuf_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_4_we0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_4_we0;
    end else begin
        col_inbuf_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_5_address0 = zext_ln69_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_5_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_address0;
    end else begin
        col_inbuf_5_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_5_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_5_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_ce0;
    end else begin
        col_inbuf_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_5_we0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_5_we0;
    end else begin
        col_inbuf_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_6_address0 = zext_ln69_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_6_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_address0;
    end else begin
        col_inbuf_6_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_6_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_6_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_ce0;
    end else begin
        col_inbuf_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_6_we0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_6_we0;
    end else begin
        col_inbuf_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_7_address0 = zext_ln69_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_7_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_address0;
    end else begin
        col_inbuf_7_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_7_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_7_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_ce0;
    end else begin
        col_inbuf_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_7_we0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_7_we0;
    end else begin
        col_inbuf_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_address0 = zext_ln69_fu_425_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_address0;
    end else begin
        col_inbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        col_inbuf_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_ce0;
    end else begin
        col_inbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        col_inbuf_we0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_col_inbuf_we0;
    end else begin
        col_inbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        col_outbuf_address0 = grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_col_outbuf_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        col_outbuf_address0 = grp_dct_1d_6_7_fu_323_dst_address0;
    end else begin
        col_outbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        col_outbuf_ce0 = grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_col_outbuf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        col_outbuf_ce0 = grp_dct_1d_6_7_fu_323_dst_ce0;
    end else begin
        col_outbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        col_outbuf_we0 = grp_dct_1d_6_7_fu_323_dst_we0;
    end else begin
        col_outbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_dst_offset = trunc_ln69_reg_560;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_dst_offset = trunc_ln58_reg_465;
    end else begin
        grp_dct_1d_6_7_fu_323_dst_offset = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_src_0_val = col_inbuf_load_reg_608;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_src_0_val = in_block_0_load_reg_520;
    end else begin
        grp_dct_1d_6_7_fu_323_src_0_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_src_1_val = col_inbuf_1_load_reg_613;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_src_1_val = in_block_1_load_reg_525;
    end else begin
        grp_dct_1d_6_7_fu_323_src_1_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_src_2_val = col_inbuf_2_load_reg_618;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_src_2_val = in_block_2_load_reg_530;
    end else begin
        grp_dct_1d_6_7_fu_323_src_2_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_src_3_val = col_inbuf_3_load_reg_623;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_src_3_val = in_block_3_load_reg_535;
    end else begin
        grp_dct_1d_6_7_fu_323_src_3_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_src_4_val = col_inbuf_4_load_reg_628;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_src_4_val = in_block_4_load_reg_540;
    end else begin
        grp_dct_1d_6_7_fu_323_src_4_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_src_5_val = col_inbuf_5_load_reg_633;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_src_5_val = in_block_5_load_reg_545;
    end else begin
        grp_dct_1d_6_7_fu_323_src_5_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_src_6_val = col_inbuf_6_load_reg_638;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_src_6_val = in_block_6_load_reg_550;
    end else begin
        grp_dct_1d_6_7_fu_323_src_6_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_dct_1d_6_7_fu_323_src_7_val = col_inbuf_7_load_reg_643;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_dct_1d_6_7_fu_323_src_7_val = in_block_7_load_reg_555;
    end else begin
        grp_dct_1d_6_7_fu_323_src_7_val = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_block_0_ce0 = 1'b1;
    end else begin
        in_block_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_block_1_ce0 = 1'b1;
    end else begin
        in_block_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_block_2_ce0 = 1'b1;
    end else begin
        in_block_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_block_3_ce0 = 1'b1;
    end else begin
        in_block_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_block_4_ce0 = 1'b1;
    end else begin
        in_block_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_block_5_ce0 = 1'b1;
    end else begin
        in_block_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_block_6_ce0 = 1'b1;
    end else begin
        in_block_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        in_block_7_ce0 = 1'b1;
    end else begin
        in_block_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        row_outbuf_address0 = grp_dct_1d_6_7_fu_323_dst_address0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        row_outbuf_address0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_row_outbuf_address0;
    end else begin
        row_outbuf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        row_outbuf_ce0 = grp_dct_1d_6_7_fu_323_dst_ce0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        row_outbuf_ce0 = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_row_outbuf_ce0;
    end else begin
        row_outbuf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        row_outbuf_we0 = grp_dct_1d_6_7_fu_323_dst_we0;
    end else begin
        row_outbuf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln58_fu_400_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_dct_1d_6_7_fu_323_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln69_fu_441_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_dct_1d_6_7_fu_323_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln58_fu_406_p2 = (i_fu_62 + 4'd1);

assign add_ln69_fu_447_p2 = (i_1_fu_106 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_dct_1d_6_7_fu_323_ap_start = grp_dct_1d_6_7_fu_323_ap_start_reg;

assign grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start = grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_ap_start_reg;

assign grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start = grp_dct_2d_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_310_ap_start_reg;

assign icmp_ln58_fu_400_p2 = ((i_fu_62 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln69_fu_441_p2 = ((i_1_fu_106 == 4'd8) ? 1'b1 : 1'b0);

assign in_block_0_address0 = zext_ln58_fu_384_p1;

assign in_block_1_address0 = zext_ln58_fu_384_p1;

assign in_block_2_address0 = zext_ln58_fu_384_p1;

assign in_block_3_address0 = zext_ln58_fu_384_p1;

assign in_block_4_address0 = zext_ln58_fu_384_p1;

assign in_block_5_address0 = zext_ln58_fu_384_p1;

assign in_block_6_address0 = zext_ln58_fu_384_p1;

assign in_block_7_address0 = zext_ln58_fu_384_p1;

assign out_block_address0 = grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_address0;

assign out_block_ce0 = grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_ce0;

assign out_block_d0 = grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_d0;

assign out_block_we0 = grp_dct_2d_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_369_out_block_we0;

assign trunc_ln58_fu_396_p1 = i_fu_62[2:0];

assign trunc_ln69_fu_437_p1 = i_1_fu_106[2:0];

assign zext_ln58_fu_384_p1 = i_fu_62;

assign zext_ln69_fu_425_p1 = i_1_fu_106;

endmodule //dct_dct_2d
