// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="fir_fir,hls_ip_2023_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.080000,HLS_SYN_LAT=70,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=548,HLS_SYN_LUT=520,HLS_VERSION=2023_1}" *)

module fir (
        ap_clk,
        ap_rst_n,
        switch_var,
        s_axi_fir_io_AWVALID,
        s_axi_fir_io_AWREADY,
        s_axi_fir_io_AWADDR,
        s_axi_fir_io_WVALID,
        s_axi_fir_io_WREADY,
        s_axi_fir_io_WDATA,
        s_axi_fir_io_WSTRB,
        s_axi_fir_io_ARVALID,
        s_axi_fir_io_ARREADY,
        s_axi_fir_io_ARADDR,
        s_axi_fir_io_RVALID,
        s_axi_fir_io_RREADY,
        s_axi_fir_io_RDATA,
        s_axi_fir_io_RRESP,
        s_axi_fir_io_BVALID,
        s_axi_fir_io_BREADY,
        s_axi_fir_io_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;
parameter    C_S_AXI_FIR_IO_DATA_WIDTH = 32;
parameter    C_S_AXI_FIR_IO_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_FIR_IO_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
input  [0:0] switch_var;
input   s_axi_fir_io_AWVALID;
output   s_axi_fir_io_AWREADY;
input  [C_S_AXI_FIR_IO_ADDR_WIDTH - 1:0] s_axi_fir_io_AWADDR;
input   s_axi_fir_io_WVALID;
output   s_axi_fir_io_WREADY;
input  [C_S_AXI_FIR_IO_DATA_WIDTH - 1:0] s_axi_fir_io_WDATA;
input  [C_S_AXI_FIR_IO_WSTRB_WIDTH - 1:0] s_axi_fir_io_WSTRB;
input   s_axi_fir_io_ARVALID;
output   s_axi_fir_io_ARREADY;
input  [C_S_AXI_FIR_IO_ADDR_WIDTH - 1:0] s_axi_fir_io_ARADDR;
output   s_axi_fir_io_RVALID;
input   s_axi_fir_io_RREADY;
output  [C_S_AXI_FIR_IO_DATA_WIDTH - 1:0] s_axi_fir_io_RDATA;
output  [1:0] s_axi_fir_io_RRESP;
output   s_axi_fir_io_BVALID;
input   s_axi_fir_io_BREADY;
output  [1:0] s_axi_fir_io_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [15:0] y;
reg    y_ap_vld;
wire  signed [15:0] x;
reg   [5:0] shift_reg_address0;
reg    shift_reg_ce0;
reg    shift_reg_we0;
reg   [15:0] shift_reg_d0;
wire   [15:0] shift_reg_q0;
wire   [15:0] shift_reg_q1;
wire    ap_CS_fsm_state2;
reg  signed [15:0] shift_reg_load_reg_159;
wire  signed [28:0] select_ln26_fu_107_p3;
reg  signed [28:0] select_ln26_reg_164;
wire  signed [27:0] trunc_ln26_fu_115_p1;
reg  signed [27:0] trunc_ln26_reg_169;
wire    ap_CS_fsm_state3;
wire   [27:0] grp_fu_103_p2;
reg   [27:0] mul_ln21_reg_179;
wire    ap_CS_fsm_state5;
reg  signed [15:0] x_read_reg_184;
wire    ap_CS_fsm_state6;
wire    grp_fir_Pipeline_loop_fu_90_ap_start;
wire    grp_fir_Pipeline_loop_fu_90_ap_done;
wire    grp_fir_Pipeline_loop_fu_90_ap_idle;
wire    grp_fir_Pipeline_loop_fu_90_ap_ready;
wire   [30:0] grp_fir_Pipeline_loop_fu_90_acc_01_out;
wire    grp_fir_Pipeline_loop_fu_90_acc_01_out_ap_vld;
wire   [5:0] grp_fir_Pipeline_loop_fu_90_shift_reg_address0;
wire    grp_fir_Pipeline_loop_fu_90_shift_reg_ce0;
wire    grp_fir_Pipeline_loop_fu_90_shift_reg_we0;
wire   [15:0] grp_fir_Pipeline_loop_fu_90_shift_reg_d0;
wire   [5:0] grp_fir_Pipeline_loop_fu_90_shift_reg_address1;
wire    grp_fir_Pipeline_loop_fu_90_shift_reg_ce1;
reg    grp_fir_Pipeline_loop_fu_90_ap_start_reg;
wire    ap_CS_fsm_state7;
reg  signed [30:0] acc_01_loc_fu_60;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire  signed [30:0] grp_fu_140_p3;
wire  signed [12:0] grp_fu_140_p0;
reg    grp_fu_140_ce;
reg   [8:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_fir_Pipeline_loop_fu_90_ap_start_reg = 1'b0;
end

fir_shift_reg_RAM_AUTO_1R1W #(
    .DataWidth( 16 ),
    .AddressRange( 58 ),
    .AddressWidth( 6 ))
shift_reg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(shift_reg_address0),
    .ce0(shift_reg_ce0),
    .we0(shift_reg_we0),
    .d0(shift_reg_d0),
    .q0(shift_reg_q0),
    .address1(grp_fir_Pipeline_loop_fu_90_shift_reg_address1),
    .ce1(grp_fir_Pipeline_loop_fu_90_shift_reg_ce1),
    .q1(shift_reg_q1)
);

fir_fir_Pipeline_loop grp_fir_Pipeline_loop_fu_90(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_fir_Pipeline_loop_fu_90_ap_start),
    .ap_done(grp_fir_Pipeline_loop_fu_90_ap_done),
    .ap_idle(grp_fir_Pipeline_loop_fu_90_ap_idle),
    .ap_ready(grp_fir_Pipeline_loop_fu_90_ap_ready),
    .sext_ln21(mul_ln21_reg_179),
    .switch_var(switch_var),
    .acc_01_out(grp_fir_Pipeline_loop_fu_90_acc_01_out),
    .acc_01_out_ap_vld(grp_fir_Pipeline_loop_fu_90_acc_01_out_ap_vld),
    .shift_reg_address0(grp_fir_Pipeline_loop_fu_90_shift_reg_address0),
    .shift_reg_ce0(grp_fir_Pipeline_loop_fu_90_shift_reg_ce0),
    .shift_reg_we0(grp_fir_Pipeline_loop_fu_90_shift_reg_we0),
    .shift_reg_d0(grp_fir_Pipeline_loop_fu_90_shift_reg_d0),
    .shift_reg_address1(grp_fir_Pipeline_loop_fu_90_shift_reg_address1),
    .shift_reg_ce1(grp_fir_Pipeline_loop_fu_90_shift_reg_ce1),
    .shift_reg_q1(shift_reg_q1)
);

fir_fir_io_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_FIR_IO_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_FIR_IO_DATA_WIDTH ))
fir_io_s_axi_U(
    .AWVALID(s_axi_fir_io_AWVALID),
    .AWREADY(s_axi_fir_io_AWREADY),
    .AWADDR(s_axi_fir_io_AWADDR),
    .WVALID(s_axi_fir_io_WVALID),
    .WREADY(s_axi_fir_io_WREADY),
    .WDATA(s_axi_fir_io_WDATA),
    .WSTRB(s_axi_fir_io_WSTRB),
    .ARVALID(s_axi_fir_io_ARVALID),
    .ARREADY(s_axi_fir_io_ARREADY),
    .ARADDR(s_axi_fir_io_ARADDR),
    .RVALID(s_axi_fir_io_RVALID),
    .RREADY(s_axi_fir_io_RREADY),
    .RDATA(s_axi_fir_io_RDATA),
    .RRESP(s_axi_fir_io_RRESP),
    .BVALID(s_axi_fir_io_BVALID),
    .BREADY(s_axi_fir_io_BREADY),
    .BRESP(s_axi_fir_io_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .y(y),
    .y_ap_vld(y_ap_vld),
    .x(x),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

fir_mul_28s_16s_28_3_1 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 28 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 28 ))
mul_28s_16s_28_3_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(trunc_ln26_reg_169),
    .din1(shift_reg_load_reg_159),
    .ce(1'b1),
    .dout(grp_fu_103_p2)
);

fir_mac_muladd_13s_16s_31s_31_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 31 ),
    .dout_WIDTH( 31 ))
mac_muladd_13s_16s_31s_31_4_1_U10(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_140_p0),
    .din1(x),
    .din2(acc_01_loc_fu_60),
    .ce(grp_fu_140_ce),
    .dout(grp_fu_140_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_fir_Pipeline_loop_fu_90_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_fir_Pipeline_loop_fu_90_ap_start_reg <= 1'b1;
        end else if ((grp_fir_Pipeline_loop_fu_90_ap_ready == 1'b1)) begin
            grp_fir_Pipeline_loop_fu_90_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_fir_Pipeline_loop_fu_90_acc_01_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
        acc_01_loc_fu_60 <= grp_fir_Pipeline_loop_fu_90_acc_01_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        mul_ln21_reg_179 <= grp_fu_103_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        select_ln26_reg_164[2] <= select_ln26_fu_107_p3[2];
select_ln26_reg_164[7] <= select_ln26_fu_107_p3[7];
select_ln26_reg_164[10] <= select_ln26_fu_107_p3[10];
select_ln26_reg_164[28 : 12] <= select_ln26_fu_107_p3[28 : 12];
        shift_reg_load_reg_159 <= shift_reg_q0;
        trunc_ln26_reg_169[2] <= trunc_ln26_fu_115_p1[2];
trunc_ln26_reg_169[7] <= trunc_ln26_fu_115_p1[7];
trunc_ln26_reg_169[10] <= trunc_ln26_fu_115_p1[10];
trunc_ln26_reg_169[27 : 12] <= trunc_ln26_fu_115_p1[27 : 12];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        x_read_reg_184 <= x;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_fir_Pipeline_loop_fu_90_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | ((grp_fir_Pipeline_loop_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7)))) begin
        grp_fu_140_ce = 1'b1;
    end else begin
        grp_fu_140_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        shift_reg_address0 = 6'd0;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        shift_reg_address0 = 6'd57;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        shift_reg_address0 = grp_fir_Pipeline_loop_fu_90_shift_reg_address0;
    end else begin
        shift_reg_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        shift_reg_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        shift_reg_ce0 = grp_fir_Pipeline_loop_fu_90_shift_reg_ce0;
    end else begin
        shift_reg_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        shift_reg_d0 = x_read_reg_184;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        shift_reg_d0 = grp_fir_Pipeline_loop_fu_90_shift_reg_d0;
    end else begin
        shift_reg_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        shift_reg_we0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        shift_reg_we0 = grp_fir_Pipeline_loop_fu_90_shift_reg_we0;
    end else begin
        shift_reg_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        y_ap_vld = 1'b1;
    end else begin
        y_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((grp_fir_Pipeline_loop_fu_90_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fir_Pipeline_loop_fu_90_ap_start = grp_fir_Pipeline_loop_fu_90_ap_start_reg;

assign grp_fu_140_p0 = select_ln26_reg_164;

assign select_ln26_fu_107_p3 = ((switch_var[0:0] == 1'b1) ? 29'd536870534 : 29'd2562);

assign trunc_ln26_fu_115_p1 = select_ln26_fu_107_p3[27:0];

assign y = {{grp_fu_140_p3[30:15]}};

always @ (posedge ap_clk) begin
    select_ln26_reg_164[1:0] <= 2'b10;
    select_ln26_reg_164[6:3] <= 4'b0000;
    select_ln26_reg_164[9:8] <= 2'b10;
    select_ln26_reg_164[11] <= 1'b1;
    trunc_ln26_reg_169[1:0] <= 2'b10;
    trunc_ln26_reg_169[6:3] <= 4'b0000;
    trunc_ln26_reg_169[9:8] <= 2'b10;
    trunc_ln26_reg_169[11] <= 1'b1;
end

endmodule //fir
