# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/Education/FPGA_Labs/Lab3/Lab3.cntrs/zedboard.xdc

# Block Designs: bd/Lab2_Block_Design/Lab2_Block_Design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design || ORIG_REF_NAME==Lab2_Block_Design} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_processing_system7_0_1/Lab2_Block_Design_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_processing_system7_0_1 || ORIG_REF_NAME==Lab2_Block_Design_processing_system7_0_1} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_0/Lab2_Block_Design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_axi_gpio_0_0 || ORIG_REF_NAME==Lab2_Block_Design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_xbar_0/Lab2_Block_Design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_xbar_0 || ORIG_REF_NAME==Lab2_Block_Design_xbar_0} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_ps7_0_axi_periph_0/Lab2_Block_Design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_ps7_0_axi_periph_0 || ORIG_REF_NAME==Lab2_Block_Design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_rst_ps7_0_100M_0/Lab2_Block_Design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_rst_ps7_0_100M_0 || ORIG_REF_NAME==Lab2_Block_Design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_1/Lab2_Block_Design_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_axi_gpio_0_1 || ORIG_REF_NAME==Lab2_Block_Design_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_auto_pc_3/Lab2_Block_Design_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_auto_pc_3 || ORIG_REF_NAME==Lab2_Block_Design_auto_pc_3} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_auto_pc_0/Lab2_Block_Design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_auto_pc_0 || ORIG_REF_NAME==Lab2_Block_Design_auto_pc_0} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_auto_pc_1/Lab2_Block_Design_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_auto_pc_1 || ORIG_REF_NAME==Lab2_Block_Design_auto_pc_1} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_auto_pc_2/Lab2_Block_Design_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_auto_pc_2 || ORIG_REF_NAME==Lab2_Block_Design_auto_pc_2} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_led_ip_0_0/Lab2_Block_Design_led_ip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_led_ip_0_0 || ORIG_REF_NAME==Lab2_Block_Design_led_ip_0_0} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_bram_ctrl_0_0/Lab2_Block_Design_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_axi_bram_ctrl_0_0 || ORIG_REF_NAME==Lab2_Block_Design_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_bram_ctrl_0_bram_0/Lab2_Block_Design_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab2_Block_Design_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==Lab2_Block_Design_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# XDC: F:/Education/FPGA_Labs/Lab3/Lab3.gen/sources_1/bd/Lab2_Block_Design/Lab2_Block_Design_ooc.xdc
