-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dct_dct,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.508000,HLS_SYN_LAT=5990,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=289,HLS_SYN_LUT=972,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000001000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000010000000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (26 downto 0) := "000000000000100000000000000";
    constant ap_ST_fsm_state16 : STD_LOGIC_VECTOR (26 downto 0) := "000000000001000000000000000";
    constant ap_ST_fsm_state17 : STD_LOGIC_VECTOR (26 downto 0) := "000000000010000000000000000";
    constant ap_ST_fsm_state18 : STD_LOGIC_VECTOR (26 downto 0) := "000000000100000000000000000";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (26 downto 0) := "000000001000000000000000000";
    constant ap_ST_fsm_state20 : STD_LOGIC_VECTOR (26 downto 0) := "000000010000000000000000000";
    constant ap_ST_fsm_state21 : STD_LOGIC_VECTOR (26 downto 0) := "000000100000000000000000000";
    constant ap_ST_fsm_state22 : STD_LOGIC_VECTOR (26 downto 0) := "000001000000000000000000000";
    constant ap_ST_fsm_state23 : STD_LOGIC_VECTOR (26 downto 0) := "000010000000000000000000000";
    constant ap_ST_fsm_state24 : STD_LOGIC_VECTOR (26 downto 0) := "000100000000000000000000000";
    constant ap_ST_fsm_state25 : STD_LOGIC_VECTOR (26 downto 0) := "001000000000000000000000000";
    constant ap_ST_fsm_state26 : STD_LOGIC_VECTOR (26 downto 0) := "010000000000000000000000000";
    constant ap_ST_fsm_state27 : STD_LOGIC_VECTOR (26 downto 0) := "100000000000000000000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001110";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_18 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv29_1000 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000001000000000000";
    constant ap_const_lv32_1C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (26 downto 0) := "000000000000000000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal dct_coeff_table_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal dct_coeff_table_ce0 : STD_LOGIC;
    signal dct_coeff_table_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln88_fu_381_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln88_reg_1005 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_4_fu_385_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_4_reg_1010 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln85_fu_399_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln85_reg_1018 : STD_LOGIC_VECTOR (3 downto 0);
    signal buf_2d_in_addr_reg_1030 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln87_fu_430_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln87_reg_1038 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln87_fu_424_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_463_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_5_reg_1048 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal add_ln58_fu_477_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln58_reg_1057 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_7_fu_496_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_7_reg_1069 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal row_outbuf_addr_1_reg_1074 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln39_fu_520_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln39_reg_1082 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal add_ln41_fu_560_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln41_reg_1100 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_fu_982_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal zext_ln66_fu_602_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln66_reg_1120 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal tmp_6_fu_606_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_6_reg_1125 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln63_fu_620_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln63_reg_1133 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal col_inbuf_addr_reg_1150 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln65_fu_673_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln65_reg_1158 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_fu_690_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_reg_1163 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal add_ln69_fu_704_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln69_reg_1172 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_3_fu_723_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_3_reg_1184 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state16 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state16 : signal is "none";
    signal col_outbuf_addr_1_reg_1189 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln39_1_fu_747_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln39_1_reg_1197 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state17 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state17 : signal is "none";
    signal add_ln41_1_fu_787_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln41_1_reg_1215 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state18 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state18 : signal is "none";
    signal grp_fu_990_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state21 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state21 : signal is "none";
    signal zext_ln77_fu_829_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln77_reg_1235 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state22 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state22 : signal is "none";
    signal tmp_s_fu_833_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_reg_1240 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln74_fu_847_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln74_reg_1248 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state23 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state23 : signal is "none";
    signal buf_2d_out_addr_reg_1265 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln76_fu_900_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln76_reg_1273 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln100_fu_913_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln100_reg_1278 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state25 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state25 : signal is "none";
    signal tmp_10_fu_917_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_10_reg_1283 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln97_fu_931_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln97_reg_1291 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state26 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state26 : signal is "none";
    signal add_ln99_fu_957_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln99_reg_1304 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln100_1_fu_963_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln100_1_reg_1309 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln99_fu_951_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal row_outbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal row_outbuf_ce0 : STD_LOGIC;
    signal row_outbuf_we0 : STD_LOGIC;
    signal row_outbuf_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal row_outbuf_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_outbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal col_outbuf_ce0 : STD_LOGIC;
    signal col_outbuf_we0 : STD_LOGIC;
    signal col_outbuf_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_outbuf_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal col_inbuf_ce0 : STD_LOGIC;
    signal col_inbuf_we0 : STD_LOGIC;
    signal col_inbuf_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_in_ce0 : STD_LOGIC;
    signal buf_2d_in_we0 : STD_LOGIC;
    signal buf_2d_in_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_out_ce0 : STD_LOGIC;
    signal buf_2d_out_we0 : STD_LOGIC;
    signal buf_2d_out_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal c_reg_261 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln85_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_reg_272 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln41_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln58_fu_471_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal n_reg_283 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln39_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_reg_294 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_2_reg_306 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal icmp_ln63_fu_614_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal k_1_reg_317 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln41_1_fu_781_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln69_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal n_1_reg_328 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln39_1_fu_741_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_339 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_3_reg_351 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state24 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state24 : signal is "none";
    signal icmp_ln74_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal c_1_reg_362 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state27 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state27 : signal is "none";
    signal icmp_ln97_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln88_2_fu_419_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln88_fu_447_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_fu_509_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_2_fu_539_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_fu_549_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln66_2_fu_652_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln66_3_fu_662_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln45_1_fu_736_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln42_5_fu_766_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln43_1_fu_776_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln77_2_fu_879_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln77_3_fu_889_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln100_2_fu_946_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln100_fu_977_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal r_fu_76 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_100 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_fu_104 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln65_fu_667_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_1_fu_108 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_1_fu_112 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln76_fu_894_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal r_1_fu_116 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln88_1_fu_410_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln88_fu_414_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln88_1_fu_436_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln_fu_440_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln45_fu_459_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln39_fu_488_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln42_fu_492_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln45_2_fu_504_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln42_1_fu_530_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln42_fu_534_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln43_fu_544_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln41_fu_566_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln45_fu_570_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln63_fu_598_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln65_fu_631_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_9_fu_639_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln66_fu_647_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln66_1_fu_635_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln66_1_fu_657_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln45_2_fu_686_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln39_1_fu_715_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln42_3_fu_719_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln45_3_fu_731_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln42_4_fu_757_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln42_1_fu_761_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln43_2_fu_771_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln41_1_fu_793_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal add_ln45_1_fu_797_p2 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln74_fu_825_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln76_fu_858_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_11_fu_866_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln77_fu_874_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln77_1_fu_862_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln77_1_fu_884_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln100_1_fu_937_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln100_fu_941_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln1_fu_971_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal ap_CS_fsm_state20 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state20 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (26 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ST_fsm_state15_blk : STD_LOGIC;
    signal ap_ST_fsm_state16_blk : STD_LOGIC;
    signal ap_ST_fsm_state17_blk : STD_LOGIC;
    signal ap_ST_fsm_state18_blk : STD_LOGIC;
    signal ap_ST_fsm_state19_blk : STD_LOGIC;
    signal ap_ST_fsm_state20_blk : STD_LOGIC;
    signal ap_ST_fsm_state21_blk : STD_LOGIC;
    signal ap_ST_fsm_state22_blk : STD_LOGIC;
    signal ap_ST_fsm_state23_blk : STD_LOGIC;
    signal ap_ST_fsm_state24_blk : STD_LOGIC;
    signal ap_ST_fsm_state25_blk : STD_LOGIC;
    signal ap_ST_fsm_state26_blk : STD_LOGIC;
    signal ap_ST_fsm_state27_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dct_mac_muladd_16s_15s_32s_32_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (14 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component dct_dct_coeff_table_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_row_outbuf_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    dct_coeff_table_U : component dct_dct_coeff_table_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_address0,
        ce0 => dct_coeff_table_ce0,
        q0 => dct_coeff_table_q0);

    row_outbuf_U : component dct_row_outbuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => row_outbuf_address0,
        ce0 => row_outbuf_ce0,
        we0 => row_outbuf_we0,
        d0 => row_outbuf_d0,
        q0 => row_outbuf_q0);

    col_outbuf_U : component dct_row_outbuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => col_outbuf_address0,
        ce0 => col_outbuf_ce0,
        we0 => col_outbuf_we0,
        d0 => col_outbuf_d0,
        q0 => col_outbuf_q0);

    col_inbuf_U : component dct_row_outbuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => col_inbuf_address0,
        ce0 => col_inbuf_ce0,
        we0 => col_inbuf_we0,
        d0 => row_outbuf_q0,
        q0 => col_inbuf_q0);

    buf_2d_in_U : component dct_row_outbuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2d_in_address0,
        ce0 => buf_2d_in_ce0,
        we0 => buf_2d_in_we0,
        d0 => input_r_q0,
        q0 => buf_2d_in_q0);

    buf_2d_out_U : component dct_row_outbuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2d_out_address0,
        ce0 => buf_2d_out_ce0,
        we0 => buf_2d_out_we0,
        d0 => col_outbuf_q0,
        q0 => buf_2d_out_q0);

    mac_muladd_16s_15s_32s_32_4_1_U1 : component dct_mac_muladd_16s_15s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => buf_2d_in_q0,
        din1 => dct_coeff_table_q0,
        din2 => tmp_reg_294,
        ce => ap_const_logic_1,
        dout => grp_fu_982_p3);

    mac_muladd_16s_15s_32s_32_4_1_U2 : component dct_mac_muladd_16s_15s_32s_32_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 16,
        din1_WIDTH => 15,
        din2_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => col_inbuf_q0,
        din1 => dct_coeff_table_q0,
        din2 => tmp_2_reg_339,
        ce => ap_const_logic_1,
        dout => grp_fu_990_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    c_1_reg_362_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln97_fu_925_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
                c_1_reg_362 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state27)) then 
                c_1_reg_362 <= add_ln99_reg_1304;
            end if; 
        end if;
    end process;

    c_reg_261_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln85_fu_393_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                c_reg_261 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                c_reg_261 <= add_ln87_reg_1038;
            end if; 
        end if;
    end process;

    i_1_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln63_fu_614_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                i_1_fu_108 <= ap_const_lv4_0;
            elsif (((icmp_ln39_1_fu_741_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                i_1_fu_108 <= add_ln69_reg_1172;
            end if; 
        end if;
    end process;

    i_2_reg_306_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln63_fu_614_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
                i_2_reg_306 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
                i_2_reg_306 <= add_ln65_reg_1158;
            end if; 
        end if;
    end process;

    i_3_reg_351_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_fu_841_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state22))) then 
                i_3_reg_351 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
                i_3_reg_351 <= add_ln76_reg_1273;
            end if; 
        end if;
    end process;

    i_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln85_fu_393_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_fu_100 <= ap_const_lv4_0;
            elsif (((icmp_ln39_fu_514_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                i_fu_100 <= add_ln58_reg_1057;
            end if; 
        end if;
    end process;

    j_1_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln69_fu_698_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then 
                j_1_fu_112 <= ap_const_lv4_0;
            elsif (((icmp_ln76_fu_894_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state23))) then 
                j_1_fu_112 <= add_ln74_reg_1248;
            end if; 
        end if;
    end process;

    j_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln58_fu_471_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                j_fu_104 <= ap_const_lv4_0;
            elsif (((icmp_ln65_fu_667_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then 
                j_fu_104 <= add_ln63_reg_1133;
            end if; 
        end if;
    end process;

    k_1_reg_317_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln69_fu_698_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state15))) then 
                k_1_reg_317 <= ap_const_lv4_0;
            elsif (((icmp_ln41_1_fu_781_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
                k_1_reg_317 <= add_ln39_1_reg_1197;
            end if; 
        end if;
    end process;

    k_reg_272_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln58_fu_471_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                k_reg_272 <= ap_const_lv4_0;
            elsif (((icmp_ln41_fu_554_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                k_reg_272 <= add_ln39_reg_1082;
            end if; 
        end if;
    end process;

    n_1_reg_328_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_1_fu_741_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                n_1_reg_328 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                n_1_reg_328 <= add_ln41_1_reg_1215;
            end if; 
        end if;
    end process;

    n_reg_283_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_514_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                n_reg_283 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                n_reg_283 <= add_ln41_reg_1100;
            end if; 
        end if;
    end process;

    r_1_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln74_fu_841_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then 
                r_1_fu_116 <= ap_const_lv4_0;
            elsif (((icmp_ln99_fu_951_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state26))) then 
                r_1_fu_116 <= add_ln97_reg_1291;
            end if; 
        end if;
    end process;

    r_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                r_fu_76 <= ap_const_lv4_0;
            elsif (((icmp_ln87_fu_424_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                r_fu_76 <= add_ln85_reg_1018;
            end if; 
        end if;
    end process;

    tmp_2_reg_339_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_1_fu_741_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state16))) then 
                tmp_2_reg_339 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state21)) then 
                tmp_2_reg_339 <= grp_fu_990_p3;
            end if; 
        end if;
    end process;

    tmp_reg_294_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln39_fu_514_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                tmp_reg_294 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                tmp_reg_294 <= grp_fu_982_p3;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state16)) then
                add_ln39_1_reg_1197 <= add_ln39_1_fu_747_p2;
                col_outbuf_addr_1_reg_1189 <= zext_ln45_1_fu_736_p1(6 - 1 downto 0);
                    tmp_3_reg_1184(5 downto 3) <= tmp_3_fu_723_p3(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                add_ln39_reg_1082 <= add_ln39_fu_520_p2;
                row_outbuf_addr_1_reg_1074 <= zext_ln45_fu_509_p1(6 - 1 downto 0);
                    tmp_7_reg_1069(5 downto 3) <= tmp_7_fu_496_p3(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state17)) then
                add_ln41_1_reg_1215 <= add_ln41_1_fu_787_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                add_ln41_reg_1100 <= add_ln41_fu_560_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                add_ln58_reg_1057 <= add_ln58_fu_477_p2;
                    tmp_5_reg_1048(5 downto 3) <= tmp_5_fu_463_p3(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state12)) then
                add_ln63_reg_1133 <= add_ln63_fu_620_p2;
                    tmp_6_reg_1125(5 downto 3) <= tmp_6_fu_606_p3(5 downto 3);
                    zext_ln66_reg_1120(3 downto 0) <= zext_ln66_fu_602_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then
                add_ln65_reg_1158 <= add_ln65_fu_673_p2;
                col_inbuf_addr_reg_1150 <= zext_ln66_3_fu_662_p1(6 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then
                add_ln69_reg_1172 <= add_ln69_fu_704_p2;
                    tmp_8_reg_1163(5 downto 3) <= tmp_8_fu_690_p3(5 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state22)) then
                add_ln74_reg_1248 <= add_ln74_fu_847_p2;
                    tmp_s_reg_1240(5 downto 3) <= tmp_s_fu_833_p3(5 downto 3);
                    zext_ln77_reg_1235(3 downto 0) <= zext_ln77_fu_829_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state23)) then
                add_ln76_reg_1273 <= add_ln76_fu_900_p2;
                buf_2d_out_addr_reg_1265 <= zext_ln77_3_fu_889_p1(6 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                add_ln85_reg_1018 <= add_ln85_fu_399_p2;
                    tmp_4_reg_1010(5 downto 3) <= tmp_4_fu_385_p3(5 downto 3);
                trunc_ln88_reg_1005 <= trunc_ln88_fu_381_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln87_reg_1038 <= add_ln87_fu_430_p2;
                buf_2d_in_addr_reg_1030 <= zext_ln88_2_fu_419_p1(6 - 1 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state25)) then
                add_ln97_reg_1291 <= add_ln97_fu_931_p2;
                    tmp_10_reg_1283(5 downto 3) <= tmp_10_fu_917_p3(5 downto 3);
                trunc_ln100_reg_1278 <= trunc_ln100_fu_913_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state26)) then
                add_ln99_reg_1304 <= add_ln99_fu_957_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln99_fu_951_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state26))) then
                trunc_ln100_1_reg_1309 <= trunc_ln100_1_fu_963_p1;
            end if;
        end if;
    end process;
    tmp_4_reg_1010(2 downto 0) <= "000";
    tmp_5_reg_1048(2 downto 0) <= "000";
    tmp_7_reg_1069(2 downto 0) <= "000";
    zext_ln66_reg_1120(5 downto 4) <= "00";
    tmp_6_reg_1125(2 downto 0) <= "000";
    tmp_8_reg_1163(2 downto 0) <= "000";
    tmp_3_reg_1184(2 downto 0) <= "000";
    zext_ln77_reg_1235(5 downto 4) <= "00";
    tmp_s_reg_1240(2 downto 0) <= "000";
    tmp_10_reg_1283(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, icmp_ln87_fu_424_p2, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state12, ap_CS_fsm_state13, ap_CS_fsm_state15, ap_CS_fsm_state16, ap_CS_fsm_state17, ap_CS_fsm_state22, ap_CS_fsm_state23, ap_CS_fsm_state25, ap_CS_fsm_state26, icmp_ln99_fu_951_p2, icmp_ln85_fu_393_p2, icmp_ln41_fu_554_p2, icmp_ln58_fu_471_p2, icmp_ln39_fu_514_p2, icmp_ln63_fu_614_p2, icmp_ln41_1_fu_781_p2, icmp_ln69_fu_698_p2, icmp_ln39_1_fu_741_p2, icmp_ln74_fu_841_p2, icmp_ln97_fu_925_p2, icmp_ln65_fu_667_p2, icmp_ln76_fu_894_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln85_fu_393_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln87_fu_424_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln58_fu_471_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((icmp_ln39_fu_514_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln41_fu_554_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state12 => 
                if (((icmp_ln63_fu_614_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state13;
                end if;
            when ap_ST_fsm_state13 => 
                if (((icmp_ln65_fu_667_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state13))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when ap_ST_fsm_state14 => 
                ap_NS_fsm <= ap_ST_fsm_state13;
            when ap_ST_fsm_state15 => 
                if (((icmp_ln69_fu_698_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state15))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state16;
                end if;
            when ap_ST_fsm_state16 => 
                if (((icmp_ln39_1_fu_741_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state16))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_state17;
                end if;
            when ap_ST_fsm_state17 => 
                if (((icmp_ln41_1_fu_781_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then
                    ap_NS_fsm <= ap_ST_fsm_state16;
                else
                    ap_NS_fsm <= ap_ST_fsm_state18;
                end if;
            when ap_ST_fsm_state18 => 
                ap_NS_fsm <= ap_ST_fsm_state19;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state20;
            when ap_ST_fsm_state20 => 
                ap_NS_fsm <= ap_ST_fsm_state21;
            when ap_ST_fsm_state21 => 
                ap_NS_fsm <= ap_ST_fsm_state17;
            when ap_ST_fsm_state22 => 
                if (((icmp_ln74_fu_841_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state22))) then
                    ap_NS_fsm <= ap_ST_fsm_state25;
                else
                    ap_NS_fsm <= ap_ST_fsm_state23;
                end if;
            when ap_ST_fsm_state23 => 
                if (((icmp_ln76_fu_894_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state23))) then
                    ap_NS_fsm <= ap_ST_fsm_state22;
                else
                    ap_NS_fsm <= ap_ST_fsm_state24;
                end if;
            when ap_ST_fsm_state24 => 
                ap_NS_fsm <= ap_ST_fsm_state23;
            when ap_ST_fsm_state25 => 
                if (((icmp_ln97_fu_925_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state26;
                end if;
            when ap_ST_fsm_state26 => 
                if (((icmp_ln99_fu_951_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state26))) then
                    ap_NS_fsm <= ap_ST_fsm_state25;
                else
                    ap_NS_fsm <= ap_ST_fsm_state27;
                end if;
            when ap_ST_fsm_state27 => 
                ap_NS_fsm <= ap_ST_fsm_state26;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln100_fu_941_p2 <= std_logic_vector(unsigned(tmp_10_reg_1283) + unsigned(zext_ln100_1_fu_937_p1));
    add_ln1_fu_971_p3 <= (trunc_ln100_reg_1278 & trunc_ln100_1_reg_1309);
    add_ln39_1_fu_747_p2 <= std_logic_vector(unsigned(k_1_reg_317) + unsigned(ap_const_lv4_1));
    add_ln39_fu_520_p2 <= std_logic_vector(unsigned(k_reg_272) + unsigned(ap_const_lv4_1));
    add_ln41_1_fu_787_p2 <= std_logic_vector(unsigned(n_1_reg_328) + unsigned(ap_const_lv4_1));
    add_ln41_fu_560_p2 <= std_logic_vector(unsigned(n_reg_283) + unsigned(ap_const_lv4_1));
    add_ln42_1_fu_761_p2 <= std_logic_vector(unsigned(tmp_3_reg_1184) + unsigned(zext_ln42_4_fu_757_p1));
    add_ln42_fu_534_p2 <= std_logic_vector(unsigned(tmp_7_reg_1069) + unsigned(zext_ln42_1_fu_530_p1));
    add_ln43_2_fu_771_p2 <= std_logic_vector(unsigned(tmp_8_reg_1163) + unsigned(zext_ln42_4_fu_757_p1));
    add_ln43_fu_544_p2 <= std_logic_vector(unsigned(tmp_5_reg_1048) + unsigned(zext_ln42_1_fu_530_p1));
    add_ln45_1_fu_797_p2 <= std_logic_vector(unsigned(trunc_ln41_1_fu_793_p1) + unsigned(ap_const_lv29_1000));
    add_ln45_2_fu_504_p2 <= std_logic_vector(unsigned(tmp_5_reg_1048) + unsigned(zext_ln42_fu_492_p1));
    add_ln45_3_fu_731_p2 <= std_logic_vector(unsigned(tmp_8_reg_1163) + unsigned(zext_ln42_3_fu_719_p1));
    add_ln45_fu_570_p2 <= std_logic_vector(unsigned(trunc_ln41_fu_566_p1) + unsigned(ap_const_lv29_1000));
    add_ln58_fu_477_p2 <= std_logic_vector(unsigned(i_fu_100) + unsigned(ap_const_lv4_1));
    add_ln63_fu_620_p2 <= std_logic_vector(unsigned(j_fu_104) + unsigned(ap_const_lv4_1));
    add_ln65_fu_673_p2 <= std_logic_vector(unsigned(i_2_reg_306) + unsigned(ap_const_lv4_1));
    add_ln66_1_fu_657_p2 <= std_logic_vector(unsigned(tmp_6_reg_1125) + unsigned(zext_ln66_1_fu_635_p1));
    add_ln66_fu_647_p2 <= std_logic_vector(unsigned(tmp_9_fu_639_p3) + unsigned(zext_ln66_reg_1120));
    add_ln69_fu_704_p2 <= std_logic_vector(unsigned(i_1_fu_108) + unsigned(ap_const_lv4_1));
    add_ln74_fu_847_p2 <= std_logic_vector(unsigned(j_1_fu_112) + unsigned(ap_const_lv4_1));
    add_ln76_fu_900_p2 <= std_logic_vector(unsigned(i_3_reg_351) + unsigned(ap_const_lv4_1));
    add_ln77_1_fu_884_p2 <= std_logic_vector(unsigned(tmp_s_reg_1240) + unsigned(zext_ln77_1_fu_862_p1));
    add_ln77_fu_874_p2 <= std_logic_vector(unsigned(tmp_11_fu_866_p3) + unsigned(zext_ln77_reg_1235));
    add_ln85_fu_399_p2 <= std_logic_vector(unsigned(r_fu_76) + unsigned(ap_const_lv4_1));
    add_ln87_fu_430_p2 <= std_logic_vector(unsigned(c_reg_261) + unsigned(ap_const_lv4_1));
    add_ln88_fu_414_p2 <= std_logic_vector(unsigned(tmp_4_reg_1010) + unsigned(zext_ln88_1_fu_410_p1));
    add_ln97_fu_931_p2 <= std_logic_vector(unsigned(r_1_fu_116) + unsigned(ap_const_lv4_1));
    add_ln99_fu_957_p2 <= std_logic_vector(unsigned(c_1_reg_362) + unsigned(ap_const_lv4_1));
    add_ln_fu_440_p3 <= (trunc_ln88_reg_1005 & trunc_ln88_1_fu_436_p1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state15 <= ap_CS_fsm(14);
    ap_CS_fsm_state16 <= ap_CS_fsm(15);
    ap_CS_fsm_state17 <= ap_CS_fsm(16);
    ap_CS_fsm_state18 <= ap_CS_fsm(17);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state20 <= ap_CS_fsm(19);
    ap_CS_fsm_state21 <= ap_CS_fsm(20);
    ap_CS_fsm_state22 <= ap_CS_fsm(21);
    ap_CS_fsm_state23 <= ap_CS_fsm(22);
    ap_CS_fsm_state24 <= ap_CS_fsm(23);
    ap_CS_fsm_state25 <= ap_CS_fsm(24);
    ap_CS_fsm_state26 <= ap_CS_fsm(25);
    ap_CS_fsm_state27 <= ap_CS_fsm(26);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;
    ap_ST_fsm_state12_blk <= ap_const_logic_0;
    ap_ST_fsm_state13_blk <= ap_const_logic_0;
    ap_ST_fsm_state14_blk <= ap_const_logic_0;
    ap_ST_fsm_state15_blk <= ap_const_logic_0;
    ap_ST_fsm_state16_blk <= ap_const_logic_0;
    ap_ST_fsm_state17_blk <= ap_const_logic_0;
    ap_ST_fsm_state18_blk <= ap_const_logic_0;
    ap_ST_fsm_state19_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state20_blk <= ap_const_logic_0;
    ap_ST_fsm_state21_blk <= ap_const_logic_0;
    ap_ST_fsm_state22_blk <= ap_const_logic_0;
    ap_ST_fsm_state23_blk <= ap_const_logic_0;
    ap_ST_fsm_state24_blk <= ap_const_logic_0;
    ap_ST_fsm_state25_blk <= ap_const_logic_0;
    ap_ST_fsm_state26_blk <= ap_const_logic_0;
    ap_ST_fsm_state27_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_CS_fsm_state25, icmp_ln97_fu_925_p2)
    begin
        if (((icmp_ln97_fu_925_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state25, icmp_ln97_fu_925_p2)
    begin
        if (((icmp_ln97_fu_925_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state25))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_address0_assign_proc : process(buf_2d_in_addr_reg_1030, ap_CS_fsm_state7, ap_CS_fsm_state4, zext_ln43_fu_549_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            buf_2d_in_address0 <= zext_ln43_fu_549_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_address0 <= buf_2d_in_addr_reg_1030;
        else 
            buf_2d_in_address0 <= "XXXXXX";
        end if; 
    end process;


    buf_2d_in_ce0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            buf_2d_in_ce0 <= ap_const_logic_1;
        else 
            buf_2d_in_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_we0_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_we0 <= ap_const_logic_1;
        else 
            buf_2d_in_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_out_address0_assign_proc : process(buf_2d_out_addr_reg_1265, ap_CS_fsm_state26, ap_CS_fsm_state24, zext_ln100_2_fu_946_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state26)) then 
            buf_2d_out_address0 <= zext_ln100_2_fu_946_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            buf_2d_out_address0 <= buf_2d_out_addr_reg_1265;
        else 
            buf_2d_out_address0 <= "XXXXXX";
        end if; 
    end process;


    buf_2d_out_ce0_assign_proc : process(ap_CS_fsm_state26, ap_CS_fsm_state24)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state24) or (ap_const_logic_1 = ap_CS_fsm_state26))) then 
            buf_2d_out_ce0 <= ap_const_logic_1;
        else 
            buf_2d_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_out_we0_assign_proc : process(ap_CS_fsm_state24)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state24)) then 
            buf_2d_out_we0 <= ap_const_logic_1;
        else 
            buf_2d_out_we0 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_address0_assign_proc : process(col_inbuf_addr_reg_1150, ap_CS_fsm_state17, ap_CS_fsm_state14, zext_ln43_1_fu_776_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            col_inbuf_address0 <= zext_ln43_1_fu_776_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            col_inbuf_address0 <= col_inbuf_addr_reg_1150;
        else 
            col_inbuf_address0 <= "XXXXXX";
        end if; 
    end process;


    col_inbuf_ce0_assign_proc : process(ap_CS_fsm_state17, ap_CS_fsm_state14)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state14) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            col_inbuf_ce0 <= ap_const_logic_1;
        else 
            col_inbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_we0_assign_proc : process(ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            col_inbuf_we0 <= ap_const_logic_1;
        else 
            col_inbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    col_outbuf_address0_assign_proc : process(col_outbuf_addr_1_reg_1189, ap_CS_fsm_state17, ap_CS_fsm_state23, zext_ln77_2_fu_879_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state23)) then 
            col_outbuf_address0 <= zext_ln77_2_fu_879_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            col_outbuf_address0 <= col_outbuf_addr_1_reg_1189;
        else 
            col_outbuf_address0 <= "XXXXXX";
        end if; 
    end process;


    col_outbuf_ce0_assign_proc : process(ap_CS_fsm_state17, ap_CS_fsm_state23)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state23) or (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            col_outbuf_ce0 <= ap_const_logic_1;
        else 
            col_outbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    col_outbuf_d0 <= add_ln45_1_fu_797_p2(28 downto 13);

    col_outbuf_we0_assign_proc : process(ap_CS_fsm_state17, icmp_ln41_1_fu_781_p2)
    begin
        if (((icmp_ln41_1_fu_781_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state17))) then 
            col_outbuf_we0 <= ap_const_logic_1;
        else 
            col_outbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_address0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state17, zext_ln42_2_fu_539_p1, zext_ln42_5_fu_766_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state17)) then 
            dct_coeff_table_address0 <= zext_ln42_5_fu_766_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            dct_coeff_table_address0 <= zext_ln42_2_fu_539_p1(6 - 1 downto 0);
        else 
            dct_coeff_table_address0 <= "XXXXXX";
        end if; 
    end process;


    dct_coeff_table_ce0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state17)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state17) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            dct_coeff_table_ce0 <= ap_const_logic_1;
        else 
            dct_coeff_table_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln39_1_fu_741_p2 <= "1" when (k_1_reg_317 = ap_const_lv4_8) else "0";
    icmp_ln39_fu_514_p2 <= "1" when (k_reg_272 = ap_const_lv4_8) else "0";
    icmp_ln41_1_fu_781_p2 <= "1" when (n_1_reg_328 = ap_const_lv4_8) else "0";
    icmp_ln41_fu_554_p2 <= "1" when (n_reg_283 = ap_const_lv4_8) else "0";
    icmp_ln58_fu_471_p2 <= "1" when (i_fu_100 = ap_const_lv4_8) else "0";
    icmp_ln63_fu_614_p2 <= "1" when (j_fu_104 = ap_const_lv4_8) else "0";
    icmp_ln65_fu_667_p2 <= "1" when (i_2_reg_306 = ap_const_lv4_8) else "0";
    icmp_ln69_fu_698_p2 <= "1" when (i_1_fu_108 = ap_const_lv4_8) else "0";
    icmp_ln74_fu_841_p2 <= "1" when (j_1_fu_112 = ap_const_lv4_8) else "0";
    icmp_ln76_fu_894_p2 <= "1" when (i_3_reg_351 = ap_const_lv4_8) else "0";
    icmp_ln85_fu_393_p2 <= "1" when (r_fu_76 = ap_const_lv4_8) else "0";
    icmp_ln87_fu_424_p2 <= "1" when (c_reg_261 = ap_const_lv4_8) else "0";
    icmp_ln97_fu_925_p2 <= "1" when (r_1_fu_116 = ap_const_lv4_8) else "0";
    icmp_ln99_fu_951_p2 <= "1" when (c_1_reg_362 = ap_const_lv4_8) else "0";
    input_r_address0 <= zext_ln88_fu_447_p1(6 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_address0 <= zext_ln100_fu_977_p1(6 - 1 downto 0);

    output_r_ce0_assign_proc : process(ap_CS_fsm_state27)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state27)) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= buf_2d_out_q0;

    output_r_we0_assign_proc : process(ap_CS_fsm_state27)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state27)) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;


    row_outbuf_address0_assign_proc : process(row_outbuf_addr_1_reg_1074, ap_CS_fsm_state7, ap_CS_fsm_state13, zext_ln66_2_fu_652_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
            row_outbuf_address0 <= zext_ln66_2_fu_652_p1(6 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            row_outbuf_address0 <= row_outbuf_addr_1_reg_1074;
        else 
            row_outbuf_address0 <= "XXXXXX";
        end if; 
    end process;


    row_outbuf_ce0_assign_proc : process(ap_CS_fsm_state7, ap_CS_fsm_state13)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state13) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            row_outbuf_ce0 <= ap_const_logic_1;
        else 
            row_outbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    row_outbuf_d0 <= add_ln45_fu_570_p2(28 downto 13);

    row_outbuf_we0_assign_proc : process(ap_CS_fsm_state7, icmp_ln41_fu_554_p2)
    begin
        if (((icmp_ln41_fu_554_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            row_outbuf_we0 <= ap_const_logic_1;
        else 
            row_outbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

    tmp_10_fu_917_p3 <= (trunc_ln100_fu_913_p1 & ap_const_lv3_0);
    tmp_11_fu_866_p3 <= (trunc_ln76_fu_858_p1 & ap_const_lv3_0);
    tmp_3_fu_723_p3 <= (trunc_ln39_1_fu_715_p1 & ap_const_lv3_0);
    tmp_4_fu_385_p3 <= (trunc_ln88_fu_381_p1 & ap_const_lv3_0);
    tmp_5_fu_463_p3 <= (trunc_ln45_fu_459_p1 & ap_const_lv3_0);
    tmp_6_fu_606_p3 <= (trunc_ln63_fu_598_p1 & ap_const_lv3_0);
    tmp_7_fu_496_p3 <= (trunc_ln39_fu_488_p1 & ap_const_lv3_0);
    tmp_8_fu_690_p3 <= (trunc_ln45_2_fu_686_p1 & ap_const_lv3_0);
    tmp_9_fu_639_p3 <= (trunc_ln65_fu_631_p1 & ap_const_lv3_0);
    tmp_s_fu_833_p3 <= (trunc_ln74_fu_825_p1 & ap_const_lv3_0);
    trunc_ln100_1_fu_963_p1 <= c_1_reg_362(3 - 1 downto 0);
    trunc_ln100_fu_913_p1 <= r_1_fu_116(3 - 1 downto 0);
    trunc_ln39_1_fu_715_p1 <= k_1_reg_317(3 - 1 downto 0);
    trunc_ln39_fu_488_p1 <= k_reg_272(3 - 1 downto 0);
    trunc_ln41_1_fu_793_p1 <= tmp_2_reg_339(29 - 1 downto 0);
    trunc_ln41_fu_566_p1 <= tmp_reg_294(29 - 1 downto 0);
    trunc_ln45_2_fu_686_p1 <= i_1_fu_108(3 - 1 downto 0);
    trunc_ln45_fu_459_p1 <= i_fu_100(3 - 1 downto 0);
    trunc_ln63_fu_598_p1 <= j_fu_104(3 - 1 downto 0);
    trunc_ln65_fu_631_p1 <= i_2_reg_306(3 - 1 downto 0);
    trunc_ln74_fu_825_p1 <= j_1_fu_112(3 - 1 downto 0);
    trunc_ln76_fu_858_p1 <= i_3_reg_351(3 - 1 downto 0);
    trunc_ln88_1_fu_436_p1 <= c_reg_261(3 - 1 downto 0);
    trunc_ln88_fu_381_p1 <= r_fu_76(3 - 1 downto 0);
    zext_ln100_1_fu_937_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_1_reg_362),6));
    zext_ln100_2_fu_946_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln100_fu_941_p2),64));
    zext_ln100_fu_977_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1_fu_971_p3),64));
    zext_ln42_1_fu_530_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_reg_283),6));
    zext_ln42_2_fu_539_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln42_fu_534_p2),64));
    zext_ln42_3_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_1_reg_317),6));
    zext_ln42_4_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(n_1_reg_328),6));
    zext_ln42_5_fu_766_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln42_1_fu_761_p2),64));
    zext_ln42_fu_492_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(k_reg_272),6));
    zext_ln43_1_fu_776_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_2_fu_771_p2),64));
    zext_ln43_fu_549_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln43_fu_544_p2),64));
    zext_ln45_1_fu_736_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln45_3_fu_731_p2),64));
    zext_ln45_fu_509_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln45_2_fu_504_p2),64));
    zext_ln66_1_fu_635_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_2_reg_306),6));
    zext_ln66_2_fu_652_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln66_fu_647_p2),64));
    zext_ln66_3_fu_662_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln66_1_fu_657_p2),64));
    zext_ln66_fu_602_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_fu_104),6));
    zext_ln77_1_fu_862_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_3_reg_351),6));
    zext_ln77_2_fu_879_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln77_fu_874_p2),64));
    zext_ln77_3_fu_889_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln77_1_fu_884_p2),64));
    zext_ln77_fu_829_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_1_fu_112),6));
    zext_ln88_1_fu_410_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(c_reg_261),6));
    zext_ln88_2_fu_419_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln88_fu_414_p2),64));
    zext_ln88_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln_fu_440_p3),64));
end behav;
