-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity fir_fir_Pipeline_loop_c2_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 16; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 59
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of fir_fir_Pipeline_loop_c2_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "0000101000000010", 1 => "0000001010010010", 2 => "0000001011010011", 3 => "0000001100001100", 
    4 => "0000001100111000", 5 => "0000001101010111", 6 => "0000001101100101", 7 => "0000001101100010", 
    8 => "0000001101001100", 9 => "0000001100100010", 10 => "0000001011100100", 11 => "0000001010010001", 
    12 => "0000001000101100", 13 => "0000000110110101", 14 => "0000000100101100", 15 => "0000000010010110", 
    16 => "1111111111110100", 17 => "1111111101001001", 18 => "1111111010011001", 19 => "1111110111101000", 
    20 => "1111110100111000", 21 => "1111110010010001", 22 => "1111101111101110", 23 => "1111101101011100", 
    24 => "1111101011011010", 25 => "1111101001101010", 26 => "1111101000010000", 27 => "1111100111001110", 
    28 => "1111100110100111", 29 => "0111100110011010", 30 => "1111100110100111", 31 => "1111100111001110", 
    32 => "1111101000010000", 33 => "1111101001101010", 34 => "1111101011011010", 35 => "1111101101011100", 
    36 => "1111101111101110", 37 => "1111110010010001", 38 => "1111110100111000", 39 => "1111110111101000", 
    40 => "1111111010011001", 41 => "1111111101001001", 42 => "1111111111110100", 43 => "0000000010010110", 
    44 => "0000000100101100", 45 => "0000000110110101", 46 => "0000001000101100", 47 => "0000001010010001", 
    48 => "0000001011100100", 49 => "0000001100100010", 50 => "0000001101001100", 51 => "0000001101100010", 
    52 => "0000001101100101", 53 => "0000001101010111", 54 => "0000001100111000", 55 => "0000001100001100", 
    56 => "0000001011010011", 57 => "0000001010010010", 58 => "0000101000000010");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

