# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Lab8_BD/Lab8_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab8_BD || ORIG_REF_NAME==Lab8_BD} -quiet] -quiet

# IP: bd/Lab8_BD/ip/Lab8_BD_processing_system7_0_0/Lab8_BD_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Lab8_BD_processing_system7_0_0 || ORIG_REF_NAME==Lab8_BD_processing_system7_0_0} -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab8/Lab8.gen/sources_1/bd/Lab8_BD/Lab8_BD_ooc.xdc
