transcript off
onbreak {quit -force}
onerror {quit -force}
transcript on

vlib work
vmap -link {F:/Education/FPGA_Labs/Lab6/Lab6.cache/compile_simlib/activehdl}
vlib activehdl/xilinx_vip
vlib activehdl/xpm
vlib activehdl/axi_infrastructure_v1_1_0
vlib activehdl/axi_vip_v1_1_14
vlib activehdl/processing_system7_vip_v1_0_16
vlib activehdl/xil_defaultlib
vlib activehdl/axi_lite_ipif_v3_0_4
vlib activehdl/lib_cdc_v1_0_2
vlib activehdl/interrupt_control_v3_1_4
vlib activehdl/axi_gpio_v2_0_30
vlib activehdl/generic_baseblocks_v2_1_0
vlib activehdl/axi_register_slice_v2_1_28
vlib activehdl/fifo_generator_v13_2_8
vlib activehdl/axi_data_fifo_v2_1_27
vlib activehdl/axi_crossbar_v2_1_29
vlib activehdl/proc_sys_reset_v5_0_13
vlib activehdl/axi_protocol_converter_v2_1_28
vlib activehdl/gigantic_mux
vlib activehdl/xlconcat_v2_1_4

vlog -work xilinx_vip  -sv2k12 "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/hdl/rst_vip_if.sv" \

vlog -work xpm  -sv2k12 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"F:/Xilinx/Vitis/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"F:/Xilinx/Vitis/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -93  \
"F:/Xilinx/Vitis/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work axi_vip_v1_1_14  -sv2k12 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ed63/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_16  -sv2k12 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_processing_system7_0_1/sim/Lab2_Block_Design_processing_system7_0_1.v" \

vcom -work axi_lite_ipif_v3_0_4 -93  \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work lib_cdc_v1_0_2 -93  \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work interrupt_control_v3_1_4 -93  \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \

vcom -work axi_gpio_v2_0_30 -93  \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/18b7/hdl/axi_gpio_v2_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_0/sim/Lab2_Block_Design_axi_gpio_0_0.vhd" \

vlog -work generic_baseblocks_v2_1_0  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_28  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/87d1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work fifo_generator_v13_2_8  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c97d/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_8 -93  \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_8  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c97d/hdl/fifo_generator_v13_2_rfs.v" \

vlog -work axi_data_fifo_v2_1_27  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/fab7/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_29  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/f8f3/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_xbar_0/sim/Lab2_Block_Design_xbar_0.v" \

vcom -work proc_sys_reset_v5_0_13 -93  \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -93  \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_rst_ps7_0_100M_0/sim/Lab2_Block_Design_rst_ps7_0_100M_0.vhd" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_1/sim/Lab2_Block_Design_axi_gpio_0_1.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../bd/Lab2_Block_Design/sim/Lab2_Block_Design.v" \

vlog -work axi_protocol_converter_v2_1_28  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/8c02/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_auto_pc_0/sim/Lab2_Block_Design_auto_pc_0.v" \

vcom -work xil_defaultlib -93  \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_axi_gpio_0_2/sim/Lab2_Block_Design_axi_gpio_0_2.vhd" \
"../../../bd/Lab2_Block_Design/ipshared/b180/math_ip.srcs/sources_1/imports/lab2/lab2_user_logic.vhd" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../bd/Lab2_Block_Design/ipshared/b180/math_ip.srcs/sources_1/imports/lab2/math_ip.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_math_ip_0_0/sim/Lab2_Block_Design_math_ip_0_0.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_ila_0_0/sim/Lab2_Block_Design_ila_0_0.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_vio_0_0/sim/Lab2_Block_Design_vio_0_0.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/sim/bd_a638_ila_lib_0.v" \

vlog -work gigantic_mux  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/e87a/hdl/gigantic_mux_v1_0_cntr.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_1/bd_a638_g_inst_0_gigantic_mux.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_1/sim/bd_a638_g_inst_0.v" \

vlog -work xlconcat_v2_1_4  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib  -v2k5 "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/ec67/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/aed8/hdl" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/1b7e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/122e/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/affe/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/20d0/hdl/verilog" "+incdir+../../../../Lab6.gen/sources_1/bd/Lab2_Block_Design/ipshared/c420/hdl" "+incdir+F:/Xilinx/Vitis/Vivado/2023.1/data/xilinx_vip/include" -l xilinx_vip -l xpm -l axi_infrastructure_v1_1_0 -l axi_vip_v1_1_14 -l processing_system7_vip_v1_0_16 -l xil_defaultlib -l axi_lite_ipif_v3_0_4 -l lib_cdc_v1_0_2 -l interrupt_control_v3_1_4 -l axi_gpio_v2_0_30 -l generic_baseblocks_v2_1_0 -l axi_register_slice_v2_1_28 -l fifo_generator_v13_2_8 -l axi_data_fifo_v2_1_27 -l axi_crossbar_v2_1_29 -l proc_sys_reset_v5_0_13 -l axi_protocol_converter_v2_1_28 -l gigantic_mux -l xlconcat_v2_1_4 \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_2/sim/bd_a638_slot_0_aw_0.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_3/sim/bd_a638_slot_0_w_0.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_4/sim/bd_a638_slot_0_b_0.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_5/sim/bd_a638_slot_0_ar_0.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_6/sim/bd_a638_slot_0_r_0.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/sim/bd_a638.v" \
"../../../bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/sim/Lab2_Block_Design_system_ila_0_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

