# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Education/FPGA_Labs/Lab8/Lab8.srcs/sources_1/bd/Lab8_BD/ip/Lab8_BD_processing_system7_0_0/Lab8_BD_processing_system7_0_0.xci
# IP: The module: 'Lab8_BD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Education/FPGA_Labs/Lab8/Lab8.gen/sources_1/bd/Lab8_BD/ip/Lab8_BD_processing_system7_0_0/Lab8_BD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab8_BD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab8/Lab8.srcs/sources_1/bd/Lab8_BD/ip/Lab8_BD_processing_system7_0_0/Lab8_BD_processing_system7_0_0.xci
# IP: The module: 'Lab8_BD_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/Education/FPGA_Labs/Lab8/Lab8.gen/sources_1/bd/Lab8_BD/ip/Lab8_BD_processing_system7_0_0/Lab8_BD_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab8_BD_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
