-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dct is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of dct is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "dct_dct,hls_ip_2023_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.508000,HLS_SYN_LAT=422,HLS_SYN_TPT=none,HLS_SYN_MEM=17,HLS_SYN_DSP=0,HLS_SYN_FF=1279,HLS_SYN_LUT=2096,HLS_VERSION=2023_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (11 downto 0) := "000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (11 downto 0) := "000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (11 downto 0) := "000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (11 downto 0) := "000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (11 downto 0) := "000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (11 downto 0) := "000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (11 downto 0) := "000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (11 downto 0) := "001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (11 downto 0) := "010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal dct_coeff_table_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_0_ce0 : STD_LOGIC;
    signal dct_coeff_table_0_q0 : STD_LOGIC_VECTOR (13 downto 0);
    signal dct_coeff_table_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_1_ce0 : STD_LOGIC;
    signal dct_coeff_table_1_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_2_ce0 : STD_LOGIC;
    signal dct_coeff_table_2_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_3_ce0 : STD_LOGIC;
    signal dct_coeff_table_3_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_4_ce0 : STD_LOGIC;
    signal dct_coeff_table_4_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_5_ce0 : STD_LOGIC;
    signal dct_coeff_table_5_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_6_ce0 : STD_LOGIC;
    signal dct_coeff_table_6_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal dct_coeff_table_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal dct_coeff_table_7_ce0 : STD_LOGIC;
    signal dct_coeff_table_7_q0 : STD_LOGIC_VECTOR (14 downto 0);
    signal row_outbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal row_outbuf_ce0 : STD_LOGIC;
    signal row_outbuf_we0 : STD_LOGIC;
    signal row_outbuf_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_outbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal col_outbuf_ce0 : STD_LOGIC;
    signal col_outbuf_we0 : STD_LOGIC;
    signal col_outbuf_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal col_inbuf_ce0 : STD_LOGIC;
    signal col_inbuf_we0 : STD_LOGIC;
    signal col_inbuf_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_ce1 : STD_LOGIC;
    signal col_inbuf_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_ce2 : STD_LOGIC;
    signal col_inbuf_q2 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_ce3 : STD_LOGIC;
    signal col_inbuf_q3 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_ce4 : STD_LOGIC;
    signal col_inbuf_q4 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_ce5 : STD_LOGIC;
    signal col_inbuf_q5 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_ce6 : STD_LOGIC;
    signal col_inbuf_q6 : STD_LOGIC_VECTOR (15 downto 0);
    signal col_inbuf_ce7 : STD_LOGIC;
    signal col_inbuf_q7 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_in_ce0 : STD_LOGIC;
    signal buf_2d_in_we0 : STD_LOGIC;
    signal buf_2d_in_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce1 : STD_LOGIC;
    signal buf_2d_in_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce2 : STD_LOGIC;
    signal buf_2d_in_q2 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce3 : STD_LOGIC;
    signal buf_2d_in_q3 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce4 : STD_LOGIC;
    signal buf_2d_in_q4 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce5 : STD_LOGIC;
    signal buf_2d_in_q5 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce6 : STD_LOGIC;
    signal buf_2d_in_q6 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_in_ce7 : STD_LOGIC;
    signal buf_2d_in_q7 : STD_LOGIC_VECTOR (15 downto 0);
    signal buf_2d_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal buf_2d_out_ce0 : STD_LOGIC;
    signal buf_2d_out_we0 : STD_LOGIC;
    signal buf_2d_out_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start : STD_LOGIC;
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_done : STD_LOGIC;
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_idle : STD_LOGIC;
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_ready : STD_LOGIC;
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_we0 : STD_LOGIC;
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_input_r_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_input_r_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_done : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_idle : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_ready : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce1 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce2 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce3 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address4 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce4 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address5 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce5 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address6 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce6 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address7 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce7 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_we0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_0_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_1_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_2_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_3_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_4_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_5_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_6_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_7_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_done : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_idle : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_ready : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_row_outbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_row_outbuf_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_we0 : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_done : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_idle : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_ready : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address1 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce1 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address2 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce2 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address3 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce3 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address4 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce4 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address5 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce5 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address6 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce6 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address7 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce7 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_we0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_0_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_0_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_1_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_2_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_3_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_4_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_5_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_6_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_7_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_done : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_idle : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_ready : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_col_outbuf_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_col_outbuf_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_we0 : STD_LOGIC;
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start : STD_LOGIC;
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done : STD_LOGIC;
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_idle : STD_LOGIC;
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_ready : STD_LOGIC;
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_buf_2d_out_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_buf_2d_out_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_ce0 : STD_LOGIC;
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_we0 : STD_LOGIC;
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component dct_dct_Pipeline_RD_Loop_Row_RD_Loop_Col IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_2d_in_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce0 : OUT STD_LOGIC;
        buf_2d_in_we0 : OUT STD_LOGIC;
        buf_2d_in_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        input_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        input_r_ce0 : OUT STD_LOGIC;
        input_r_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_2d_in_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce0 : OUT STD_LOGIC;
        buf_2d_in_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_2d_in_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce1 : OUT STD_LOGIC;
        buf_2d_in_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_2d_in_address2 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce2 : OUT STD_LOGIC;
        buf_2d_in_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_2d_in_address3 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce3 : OUT STD_LOGIC;
        buf_2d_in_q3 : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_2d_in_address4 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce4 : OUT STD_LOGIC;
        buf_2d_in_q4 : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_2d_in_address5 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce5 : OUT STD_LOGIC;
        buf_2d_in_q5 : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_2d_in_address6 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce6 : OUT STD_LOGIC;
        buf_2d_in_q6 : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_2d_in_address7 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_in_ce7 : OUT STD_LOGIC;
        buf_2d_in_q7 : IN STD_LOGIC_VECTOR (15 downto 0);
        row_outbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        row_outbuf_ce0 : OUT STD_LOGIC;
        row_outbuf_we0 : OUT STD_LOGIC;
        row_outbuf_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        dct_coeff_table_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_0_ce0 : OUT STD_LOGIC;
        dct_coeff_table_0_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        dct_coeff_table_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_1_ce0 : OUT STD_LOGIC;
        dct_coeff_table_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_2_ce0 : OUT STD_LOGIC;
        dct_coeff_table_2_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_3_ce0 : OUT STD_LOGIC;
        dct_coeff_table_3_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_4_ce0 : OUT STD_LOGIC;
        dct_coeff_table_4_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_5_ce0 : OUT STD_LOGIC;
        dct_coeff_table_5_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_6_ce0 : OUT STD_LOGIC;
        dct_coeff_table_6_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_7_ce0 : OUT STD_LOGIC;
        dct_coeff_table_7_q0 : IN STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        row_outbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        row_outbuf_ce0 : OUT STD_LOGIC;
        row_outbuf_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_inbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce0 : OUT STD_LOGIC;
        col_inbuf_we0 : OUT STD_LOGIC;
        col_inbuf_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        col_inbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce0 : OUT STD_LOGIC;
        col_inbuf_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_inbuf_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce1 : OUT STD_LOGIC;
        col_inbuf_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_inbuf_address2 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce2 : OUT STD_LOGIC;
        col_inbuf_q2 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_inbuf_address3 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce3 : OUT STD_LOGIC;
        col_inbuf_q3 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_inbuf_address4 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce4 : OUT STD_LOGIC;
        col_inbuf_q4 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_inbuf_address5 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce5 : OUT STD_LOGIC;
        col_inbuf_q5 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_inbuf_address6 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce6 : OUT STD_LOGIC;
        col_inbuf_q6 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_inbuf_address7 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_inbuf_ce7 : OUT STD_LOGIC;
        col_inbuf_q7 : IN STD_LOGIC_VECTOR (15 downto 0);
        col_outbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_outbuf_ce0 : OUT STD_LOGIC;
        col_outbuf_we0 : OUT STD_LOGIC;
        col_outbuf_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        dct_coeff_table_0_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_0_ce0 : OUT STD_LOGIC;
        dct_coeff_table_0_q0 : IN STD_LOGIC_VECTOR (13 downto 0);
        dct_coeff_table_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_1_ce0 : OUT STD_LOGIC;
        dct_coeff_table_1_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_2_ce0 : OUT STD_LOGIC;
        dct_coeff_table_2_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_3_ce0 : OUT STD_LOGIC;
        dct_coeff_table_3_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_4_ce0 : OUT STD_LOGIC;
        dct_coeff_table_4_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_5_ce0 : OUT STD_LOGIC;
        dct_coeff_table_5_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_6_ce0 : OUT STD_LOGIC;
        dct_coeff_table_6_q0 : IN STD_LOGIC_VECTOR (14 downto 0);
        dct_coeff_table_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        dct_coeff_table_7_ce0 : OUT STD_LOGIC;
        dct_coeff_table_7_q0 : IN STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        col_outbuf_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        col_outbuf_ce0 : OUT STD_LOGIC;
        col_outbuf_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        buf_2d_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_out_ce0 : OUT STD_LOGIC;
        buf_2d_out_we0 : OUT STD_LOGIC;
        buf_2d_out_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_dct_Pipeline_WR_Loop_Row_WR_Loop_Col IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        buf_2d_out_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        buf_2d_out_ce0 : OUT STD_LOGIC;
        buf_2d_out_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        output_r_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        output_r_ce0 : OUT STD_LOGIC;
        output_r_we0 : OUT STD_LOGIC;
        output_r_d0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_dct_coeff_table_0_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (13 downto 0) );
    end component;


    component dct_dct_coeff_table_1_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_coeff_table_2_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_coeff_table_3_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_coeff_table_4_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_coeff_table_5_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_coeff_table_6_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_dct_coeff_table_7_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (14 downto 0) );
    end component;


    component dct_row_outbuf_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component dct_col_inbuf_RAM_1WNR_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (15 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address2 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce2 : IN STD_LOGIC;
        q2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address3 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce3 : IN STD_LOGIC;
        q3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address4 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce4 : IN STD_LOGIC;
        q4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address5 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce5 : IN STD_LOGIC;
        q5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address6 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce6 : IN STD_LOGIC;
        q6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address7 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce7 : IN STD_LOGIC;
        q7 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    dct_coeff_table_0_U : component dct_dct_coeff_table_0_ROM_AUTO_1R
    generic map (
        DataWidth => 14,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_0_address0,
        ce0 => dct_coeff_table_0_ce0,
        q0 => dct_coeff_table_0_q0);

    dct_coeff_table_1_U : component dct_dct_coeff_table_1_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_1_address0,
        ce0 => dct_coeff_table_1_ce0,
        q0 => dct_coeff_table_1_q0);

    dct_coeff_table_2_U : component dct_dct_coeff_table_2_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_2_address0,
        ce0 => dct_coeff_table_2_ce0,
        q0 => dct_coeff_table_2_q0);

    dct_coeff_table_3_U : component dct_dct_coeff_table_3_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_3_address0,
        ce0 => dct_coeff_table_3_ce0,
        q0 => dct_coeff_table_3_q0);

    dct_coeff_table_4_U : component dct_dct_coeff_table_4_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_4_address0,
        ce0 => dct_coeff_table_4_ce0,
        q0 => dct_coeff_table_4_q0);

    dct_coeff_table_5_U : component dct_dct_coeff_table_5_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_5_address0,
        ce0 => dct_coeff_table_5_ce0,
        q0 => dct_coeff_table_5_q0);

    dct_coeff_table_6_U : component dct_dct_coeff_table_6_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_6_address0,
        ce0 => dct_coeff_table_6_ce0,
        q0 => dct_coeff_table_6_q0);

    dct_coeff_table_7_U : component dct_dct_coeff_table_7_ROM_AUTO_1R
    generic map (
        DataWidth => 15,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => dct_coeff_table_7_address0,
        ce0 => dct_coeff_table_7_ce0,
        q0 => dct_coeff_table_7_q0);

    row_outbuf_U : component dct_row_outbuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => row_outbuf_address0,
        ce0 => row_outbuf_ce0,
        we0 => row_outbuf_we0,
        d0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_d0,
        q0 => row_outbuf_q0);

    col_outbuf_U : component dct_row_outbuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => col_outbuf_address0,
        ce0 => col_outbuf_ce0,
        we0 => col_outbuf_we0,
        d0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_d0,
        q0 => col_outbuf_q0);

    col_inbuf_U : component dct_col_inbuf_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => col_inbuf_address0,
        ce0 => col_inbuf_ce0,
        we0 => col_inbuf_we0,
        d0 => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_d0,
        q0 => col_inbuf_q0,
        address1 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address1,
        ce1 => col_inbuf_ce1,
        q1 => col_inbuf_q1,
        address2 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address2,
        ce2 => col_inbuf_ce2,
        q2 => col_inbuf_q2,
        address3 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address3,
        ce3 => col_inbuf_ce3,
        q3 => col_inbuf_q3,
        address4 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address4,
        ce4 => col_inbuf_ce4,
        q4 => col_inbuf_q4,
        address5 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address5,
        ce5 => col_inbuf_ce5,
        q5 => col_inbuf_q5,
        address6 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address6,
        ce6 => col_inbuf_ce6,
        q6 => col_inbuf_q6,
        address7 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address7,
        ce7 => col_inbuf_ce7,
        q7 => col_inbuf_q7);

    buf_2d_in_U : component dct_col_inbuf_RAM_1WNR_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2d_in_address0,
        ce0 => buf_2d_in_ce0,
        we0 => buf_2d_in_we0,
        d0 => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_d0,
        q0 => buf_2d_in_q0,
        address1 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address1,
        ce1 => buf_2d_in_ce1,
        q1 => buf_2d_in_q1,
        address2 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address2,
        ce2 => buf_2d_in_ce2,
        q2 => buf_2d_in_q2,
        address3 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address3,
        ce3 => buf_2d_in_ce3,
        q3 => buf_2d_in_q3,
        address4 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address4,
        ce4 => buf_2d_in_ce4,
        q4 => buf_2d_in_q4,
        address5 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address5,
        ce5 => buf_2d_in_ce5,
        q5 => buf_2d_in_q5,
        address6 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address6,
        ce6 => buf_2d_in_ce6,
        q6 => buf_2d_in_q6,
        address7 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address7,
        ce7 => buf_2d_in_ce7,
        q7 => buf_2d_in_q7);

    buf_2d_out_U : component dct_row_outbuf_RAM_AUTO_1R1W
    generic map (
        DataWidth => 16,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => buf_2d_out_address0,
        ce0 => buf_2d_out_ce0,
        we0 => buf_2d_out_we0,
        d0 => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_d0,
        q0 => buf_2d_out_q0);

    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70 : component dct_dct_Pipeline_RD_Loop_Row_RD_Loop_Col
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start,
        ap_done => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_done,
        ap_idle => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_idle,
        ap_ready => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_ready,
        buf_2d_in_address0 => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_address0,
        buf_2d_in_ce0 => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_ce0,
        buf_2d_in_we0 => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_we0,
        buf_2d_in_d0 => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_d0,
        input_r_address0 => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_input_r_address0,
        input_r_ce0 => grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_input_r_ce0,
        input_r_q0 => input_r_q0);

    grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78 : component dct_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start,
        ap_done => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_done,
        ap_idle => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_idle,
        ap_ready => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_ready,
        buf_2d_in_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address0,
        buf_2d_in_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce0,
        buf_2d_in_q0 => buf_2d_in_q0,
        buf_2d_in_address1 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address1,
        buf_2d_in_ce1 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce1,
        buf_2d_in_q1 => buf_2d_in_q1,
        buf_2d_in_address2 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address2,
        buf_2d_in_ce2 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce2,
        buf_2d_in_q2 => buf_2d_in_q2,
        buf_2d_in_address3 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address3,
        buf_2d_in_ce3 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce3,
        buf_2d_in_q3 => buf_2d_in_q3,
        buf_2d_in_address4 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address4,
        buf_2d_in_ce4 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce4,
        buf_2d_in_q4 => buf_2d_in_q4,
        buf_2d_in_address5 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address5,
        buf_2d_in_ce5 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce5,
        buf_2d_in_q5 => buf_2d_in_q5,
        buf_2d_in_address6 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address6,
        buf_2d_in_ce6 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce6,
        buf_2d_in_q6 => buf_2d_in_q6,
        buf_2d_in_address7 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address7,
        buf_2d_in_ce7 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce7,
        buf_2d_in_q7 => buf_2d_in_q7,
        row_outbuf_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_address0,
        row_outbuf_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_ce0,
        row_outbuf_we0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_we0,
        row_outbuf_d0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_d0,
        dct_coeff_table_0_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_0_address0,
        dct_coeff_table_0_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_0_ce0,
        dct_coeff_table_0_q0 => dct_coeff_table_0_q0,
        dct_coeff_table_1_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_1_address0,
        dct_coeff_table_1_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_1_ce0,
        dct_coeff_table_1_q0 => dct_coeff_table_1_q0,
        dct_coeff_table_2_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_2_address0,
        dct_coeff_table_2_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_2_ce0,
        dct_coeff_table_2_q0 => dct_coeff_table_2_q0,
        dct_coeff_table_3_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_3_address0,
        dct_coeff_table_3_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_3_ce0,
        dct_coeff_table_3_q0 => dct_coeff_table_3_q0,
        dct_coeff_table_4_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_4_address0,
        dct_coeff_table_4_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_4_ce0,
        dct_coeff_table_4_q0 => dct_coeff_table_4_q0,
        dct_coeff_table_5_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_5_address0,
        dct_coeff_table_5_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_5_ce0,
        dct_coeff_table_5_q0 => dct_coeff_table_5_q0,
        dct_coeff_table_6_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_6_address0,
        dct_coeff_table_6_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_6_ce0,
        dct_coeff_table_6_q0 => dct_coeff_table_6_q0,
        dct_coeff_table_7_address0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_7_address0,
        dct_coeff_table_7_ce0 => grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_7_ce0,
        dct_coeff_table_7_q0 => dct_coeff_table_7_q0);

    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100 : component dct_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start,
        ap_done => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_done,
        ap_idle => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_idle,
        ap_ready => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_ready,
        row_outbuf_address0 => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_row_outbuf_address0,
        row_outbuf_ce0 => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_row_outbuf_ce0,
        row_outbuf_q0 => row_outbuf_q0,
        col_inbuf_address0 => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_address0,
        col_inbuf_ce0 => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_ce0,
        col_inbuf_we0 => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_we0,
        col_inbuf_d0 => grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_d0);

    grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106 : component dct_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start,
        ap_done => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_done,
        ap_idle => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_idle,
        ap_ready => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_ready,
        col_inbuf_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address0,
        col_inbuf_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce0,
        col_inbuf_q0 => col_inbuf_q0,
        col_inbuf_address1 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address1,
        col_inbuf_ce1 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce1,
        col_inbuf_q1 => col_inbuf_q1,
        col_inbuf_address2 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address2,
        col_inbuf_ce2 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce2,
        col_inbuf_q2 => col_inbuf_q2,
        col_inbuf_address3 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address3,
        col_inbuf_ce3 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce3,
        col_inbuf_q3 => col_inbuf_q3,
        col_inbuf_address4 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address4,
        col_inbuf_ce4 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce4,
        col_inbuf_q4 => col_inbuf_q4,
        col_inbuf_address5 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address5,
        col_inbuf_ce5 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce5,
        col_inbuf_q5 => col_inbuf_q5,
        col_inbuf_address6 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address6,
        col_inbuf_ce6 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce6,
        col_inbuf_q6 => col_inbuf_q6,
        col_inbuf_address7 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address7,
        col_inbuf_ce7 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce7,
        col_inbuf_q7 => col_inbuf_q7,
        col_outbuf_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_address0,
        col_outbuf_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_ce0,
        col_outbuf_we0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_we0,
        col_outbuf_d0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_d0,
        dct_coeff_table_0_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_0_address0,
        dct_coeff_table_0_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_0_ce0,
        dct_coeff_table_0_q0 => dct_coeff_table_0_q0,
        dct_coeff_table_1_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_1_address0,
        dct_coeff_table_1_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_1_ce0,
        dct_coeff_table_1_q0 => dct_coeff_table_1_q0,
        dct_coeff_table_2_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_2_address0,
        dct_coeff_table_2_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_2_ce0,
        dct_coeff_table_2_q0 => dct_coeff_table_2_q0,
        dct_coeff_table_3_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_3_address0,
        dct_coeff_table_3_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_3_ce0,
        dct_coeff_table_3_q0 => dct_coeff_table_3_q0,
        dct_coeff_table_4_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_4_address0,
        dct_coeff_table_4_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_4_ce0,
        dct_coeff_table_4_q0 => dct_coeff_table_4_q0,
        dct_coeff_table_5_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_5_address0,
        dct_coeff_table_5_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_5_ce0,
        dct_coeff_table_5_q0 => dct_coeff_table_5_q0,
        dct_coeff_table_6_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_6_address0,
        dct_coeff_table_6_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_6_ce0,
        dct_coeff_table_6_q0 => dct_coeff_table_6_q0,
        dct_coeff_table_7_address0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_7_address0,
        dct_coeff_table_7_ce0 => grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_7_ce0,
        dct_coeff_table_7_q0 => dct_coeff_table_7_q0);

    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128 : component dct_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start,
        ap_done => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_done,
        ap_idle => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_idle,
        ap_ready => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_ready,
        col_outbuf_address0 => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_col_outbuf_address0,
        col_outbuf_ce0 => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_col_outbuf_ce0,
        col_outbuf_q0 => col_outbuf_q0,
        buf_2d_out_address0 => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_address0,
        buf_2d_out_ce0 => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_ce0,
        buf_2d_out_we0 => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_we0,
        buf_2d_out_d0 => grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_d0);

    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134 : component dct_dct_Pipeline_WR_Loop_Row_WR_Loop_Col
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start,
        ap_done => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done,
        ap_idle => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_idle,
        ap_ready => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_ready,
        buf_2d_out_address0 => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_buf_2d_out_address0,
        buf_2d_out_ce0 => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_buf_2d_out_ce0,
        buf_2d_out_q0 => buf_2d_out_q0,
        output_r_address0 => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_address0,
        output_r_ce0 => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_ce0,
        output_r_we0 => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_we0,
        output_r_d0 => grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_d0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                    grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_ready = ap_const_logic_1)) then 
                    grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_ready = ap_const_logic_1)) then 
                    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_ready = ap_const_logic_1)) then 
                    grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
                    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_ready = ap_const_logic_1)) then 
                    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_ready = ap_const_logic_1)) then 
                    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_ready = ap_const_logic_1)) then 
                    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_done, grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_done, grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_done, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_done, grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_done, grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4, ap_CS_fsm_state6, ap_CS_fsm_state8, ap_CS_fsm_state10, ap_CS_fsm_state12)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if (((grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state12;
            when ap_ST_fsm_state12 => 
                if (((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_done)
    begin
        if ((grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state12_blk_assign_proc : process(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done)
    begin
        if ((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_done)
    begin
        if ((grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_done)
    begin
        if ((grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_done)
    begin
        if ((grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_done)
    begin
        if ((grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done, ap_CS_fsm_state12)
    begin
        if (((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done, ap_CS_fsm_state12)
    begin
        if (((grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state12))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_address0_assign_proc : process(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_address0, grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_2d_in_address0 <= grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_address0;
        else 
            buf_2d_in_address0 <= "XXXXXX";
        end if; 
    end process;


    buf_2d_in_ce0_assign_proc : process(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_ce0, grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_2d_in_ce0 <= grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_ce0;
        else 
            buf_2d_in_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce1_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_ce1 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce1;
        else 
            buf_2d_in_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce2_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_ce2 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce2;
        else 
            buf_2d_in_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce3_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce3, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_ce3 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce3;
        else 
            buf_2d_in_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce4_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce4, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_ce4 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce4;
        else 
            buf_2d_in_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce5_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce5, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_ce5 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce5;
        else 
            buf_2d_in_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce6_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce6, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_ce6 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce6;
        else 
            buf_2d_in_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_ce7_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce7, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            buf_2d_in_ce7 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_buf_2d_in_ce7;
        else 
            buf_2d_in_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_in_we0_assign_proc : process(grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_we0, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            buf_2d_in_we0 <= grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_buf_2d_in_we0;
        else 
            buf_2d_in_we0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_out_address0_assign_proc : process(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_address0, grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_buf_2d_out_address0, ap_CS_fsm_state10, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            buf_2d_out_address0 <= grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_buf_2d_out_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            buf_2d_out_address0 <= grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_address0;
        else 
            buf_2d_out_address0 <= "XXXXXX";
        end if; 
    end process;


    buf_2d_out_ce0_assign_proc : process(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_ce0, grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_buf_2d_out_ce0, ap_CS_fsm_state10, ap_CS_fsm_state12)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            buf_2d_out_ce0 <= grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_buf_2d_out_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            buf_2d_out_ce0 <= grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_ce0;
        else 
            buf_2d_out_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_2d_out_we0_assign_proc : process(grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_we0, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            buf_2d_out_we0 <= grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_buf_2d_out_we0;
        else 
            buf_2d_out_we0 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_address0_assign_proc : process(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            col_inbuf_address0 <= grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_address0;
        else 
            col_inbuf_address0 <= "XXXXXX";
        end if; 
    end process;


    col_inbuf_ce0_assign_proc : process(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce0, ap_CS_fsm_state6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            col_inbuf_ce0 <= grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_ce0;
        else 
            col_inbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_ce1_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce1, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_ce1 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce1;
        else 
            col_inbuf_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_ce2_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce2, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_ce2 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce2;
        else 
            col_inbuf_ce2 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_ce3_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce3, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_ce3 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce3;
        else 
            col_inbuf_ce3 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_ce4_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_ce4 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce4;
        else 
            col_inbuf_ce4 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_ce5_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce5, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_ce5 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce5;
        else 
            col_inbuf_ce5 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_ce6_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce6, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_ce6 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce6;
        else 
            col_inbuf_ce6 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_ce7_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce7, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_inbuf_ce7 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_inbuf_ce7;
        else 
            col_inbuf_ce7 <= ap_const_logic_0;
        end if; 
    end process;


    col_inbuf_we0_assign_proc : process(grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_we0, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            col_inbuf_we0 <= grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_col_inbuf_we0;
        else 
            col_inbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    col_outbuf_address0_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_address0, grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_col_outbuf_address0, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            col_outbuf_address0 <= grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_col_outbuf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_outbuf_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_address0;
        else 
            col_outbuf_address0 <= "XXXXXX";
        end if; 
    end process;


    col_outbuf_ce0_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_ce0, grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_col_outbuf_ce0, ap_CS_fsm_state8, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            col_outbuf_ce0 <= grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_col_outbuf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_outbuf_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_ce0;
        else 
            col_outbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    col_outbuf_we0_assign_proc : process(grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_we0, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            col_outbuf_we0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_col_outbuf_we0;
        else 
            col_outbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_0_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_0_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_0_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_0_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_0_address0;
        else 
            dct_coeff_table_0_address0 <= "XXX";
        end if; 
    end process;


    dct_coeff_table_0_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_0_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_0_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_0_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_0_ce0;
        else 
            dct_coeff_table_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_1_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_1_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_1_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_1_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_1_address0;
        else 
            dct_coeff_table_1_address0 <= "XXX";
        end if; 
    end process;


    dct_coeff_table_1_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_1_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_1_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_1_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_1_ce0;
        else 
            dct_coeff_table_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_2_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_2_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_2_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_2_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_2_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_2_address0;
        else 
            dct_coeff_table_2_address0 <= "XXX";
        end if; 
    end process;


    dct_coeff_table_2_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_2_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_2_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_2_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_2_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_2_ce0;
        else 
            dct_coeff_table_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_3_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_3_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_3_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_3_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_3_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_3_address0;
        else 
            dct_coeff_table_3_address0 <= "XXX";
        end if; 
    end process;


    dct_coeff_table_3_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_3_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_3_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_3_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_3_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_3_ce0;
        else 
            dct_coeff_table_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_4_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_4_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_4_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_4_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_4_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_4_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_4_address0;
        else 
            dct_coeff_table_4_address0 <= "XXX";
        end if; 
    end process;


    dct_coeff_table_4_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_4_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_4_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_4_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_4_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_4_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_4_ce0;
        else 
            dct_coeff_table_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_5_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_5_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_5_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_5_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_5_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_5_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_5_address0;
        else 
            dct_coeff_table_5_address0 <= "XXX";
        end if; 
    end process;


    dct_coeff_table_5_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_5_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_5_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_5_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_5_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_5_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_5_ce0;
        else 
            dct_coeff_table_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_6_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_6_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_6_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_6_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_6_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_6_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_6_address0;
        else 
            dct_coeff_table_6_address0 <= "XXX";
        end if; 
    end process;


    dct_coeff_table_6_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_6_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_6_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_6_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_6_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_6_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_6_ce0;
        else 
            dct_coeff_table_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    dct_coeff_table_7_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_7_address0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_7_address0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_7_address0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_7_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_7_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_7_address0;
        else 
            dct_coeff_table_7_address0 <= "XXX";
        end if; 
    end process;


    dct_coeff_table_7_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_7_ce0, grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_7_ce0, ap_CS_fsm_state4, ap_CS_fsm_state8)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            dct_coeff_table_7_ce0 <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_dct_coeff_table_7_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            dct_coeff_table_7_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_dct_coeff_table_7_ce0;
        else 
            dct_coeff_table_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start <= grp_dct_Pipeline_Col_DCT_Loop_DCT_Outer_Loop_fu_106_ap_start_reg;
    grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start <= grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_ap_start_reg;
    grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_ap_start_reg;
    grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start <= grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_ap_start_reg;
    grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start <= grp_dct_Pipeline_Xpose_Col_Outer_Loop_Xpose_Col_Inner_Loop_fu_128_ap_start_reg;
    grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start <= grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_ap_start_reg;
    input_r_address0 <= grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_input_r_address0;
    input_r_ce0 <= grp_dct_Pipeline_RD_Loop_Row_RD_Loop_Col_fu_70_input_r_ce0;
    output_r_address0 <= grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_address0;
    output_r_ce0 <= grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_ce0;
    output_r_d0 <= grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_d0;
    output_r_we0 <= grp_dct_Pipeline_WR_Loop_Row_WR_Loop_Col_fu_134_output_r_we0;

    row_outbuf_address0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_address0, grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_row_outbuf_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_outbuf_address0 <= grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_row_outbuf_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_outbuf_address0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_address0;
        else 
            row_outbuf_address0 <= "XXXXXX";
        end if; 
    end process;


    row_outbuf_ce0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_ce0, grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_row_outbuf_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            row_outbuf_ce0 <= grp_dct_Pipeline_Xpose_Row_Outer_Loop_Xpose_Row_Inner_Loop_fu_100_row_outbuf_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_outbuf_ce0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_ce0;
        else 
            row_outbuf_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    row_outbuf_we0_assign_proc : process(grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_we0, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            row_outbuf_we0 <= grp_dct_Pipeline_Row_DCT_Loop_DCT_Outer_Loop_fu_78_row_outbuf_we0;
        else 
            row_outbuf_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
