# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.srcs/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/Lab2_Block_Design_system_ila_0_0.xci
# IP: The module: 'Lab2_Block_Design_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/bd_a638.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638 || ORIG_REF_NAME==bd_a638} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/bd_a638_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_ila_lib_0 || ORIG_REF_NAME==bd_a638_ila_lib_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_1/bd_a638_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_g_inst_0 || ORIG_REF_NAME==bd_a638_g_inst_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_2/bd_a638_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_aw_0 || ORIG_REF_NAME==bd_a638_slot_0_aw_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_3/bd_a638_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_w_0 || ORIG_REF_NAME==bd_a638_slot_0_w_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_4/bd_a638_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_b_0 || ORIG_REF_NAME==bd_a638_slot_0_b_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_5/bd_a638_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_ar_0 || ORIG_REF_NAME==bd_a638_slot_0_ar_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_6/bd_a638_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_r_0 || ORIG_REF_NAME==bd_a638_slot_0_r_0} -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a638_ila_lib_0 || ORIG_REF_NAME==bd_a638_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a638_ila_lib_0 || ORIG_REF_NAME==bd_a638_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/bd_a638_ila_lib_0_ooc.xdc

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/bd_a638_ooc.xdc

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/Lab2_Block_Design_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.srcs/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/Lab2_Block_Design_system_ila_0_0.xci
# IP: The module: 'Lab2_Block_Design_system_ila_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/bd_a638.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638 || ORIG_REF_NAME==bd_a638} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/bd_a638_ila_lib_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_ila_lib_0 || ORIG_REF_NAME==bd_a638_ila_lib_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_1/bd_a638_g_inst_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_g_inst_0 || ORIG_REF_NAME==bd_a638_g_inst_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_2/bd_a638_slot_0_aw_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_aw_0 || ORIG_REF_NAME==bd_a638_slot_0_aw_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_3/bd_a638_slot_0_w_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_w_0 || ORIG_REF_NAME==bd_a638_slot_0_w_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_4/bd_a638_slot_0_b_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_b_0 || ORIG_REF_NAME==bd_a638_slot_0_b_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_5/bd_a638_slot_0_ar_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_ar_0 || ORIG_REF_NAME==bd_a638_slot_0_ar_0} -quiet] -quiet

# IP: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_6/bd_a638_slot_0_r_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_a638_slot_0_r_0 || ORIG_REF_NAME==bd_a638_slot_0_r_0} -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a638_ila_lib_0 || ORIG_REF_NAME==bd_a638_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_a638_ila_lib_0 || ORIG_REF_NAME==bd_a638_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/ip/ip_0/bd_a638_ila_lib_0_ooc.xdc

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/bd_0/bd_a638_ooc.xdc

# XDC: f:/Education/FPGA_Labs/Lab6/Lab6.gen/sources_1/bd/Lab2_Block_Design/ip/Lab2_Block_Design_system_ila_0_0/Lab2_Block_Design_system_ila_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Lab2_Block_Design_system_ila_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
